window.STUDY_EXTRA_QUESTION_DATA = [
  {
    id: "audio-mid-001",
    source: "音声工学 中間",
    category: "audio",
    number: 1,
    prompt: "日本語について、次の空欄に入る組み合わせを答えなさい。\n日本語は世界で（イ）番目に話者数が多いが、系統が（ロ）孤立した言語である。基礎語彙や（ハ）体系はオーストロネシア語族に由来、（ニ）体系はアルタイ諸語に由来すると言われている。",
    answer: "イ = 9 / ロ = 不明な / ハ = 音韻 / ニ = 文法",
    type: "matching",
    choices: ["a: 90", "b: 9", "c: 明らかな", "d: 不明な", "e: 文法", "f: 音韻"],
    images: []
  },
  {
    id: "audio-mid-002",
    source: "音声工学 中間",
    category: "audio",
    number: 2,
    prompt: "音が発生する3つの原因と音声での対応について、正しい組み合わせを答えなさい。\n（イ）物体の振動、（ロ）空気の乱流、（ハ）空気の急激な膨張や収縮。",
    answer: "イ = 母音 / ロ = 摩擦音 / ハ = 破裂音",
    type: "matching",
    choices: ["a: 母音", "b: 摩擦音", "c: 破裂音"],
    images: []
  },
  {
    id: "audio-mid-003",
    source: "音声工学 中間",
    category: "audio",
    number: 3,
    prompt: "「ぴ」の頭子音を有声化した仮名を書きなさい。",
    answer: "び",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-004",
    source: "音声工学 中間",
    category: "audio",
    number: 4,
    prompt: "あらゆる言語の音声を文字で表記するために、国際音声学会が定めた記号を3文字のアルファベットで答えなさい。",
    answer: "IPA",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-005",
    source: "音声工学 中間",
    category: "audio",
    number: 5,
    prompt: "次の語はそれぞれ何モーラか答えなさい。",
    answer: "東京都 = 5 / チョコレート = 5 / 関東 = 4 / サッカー = 4",
    type: "matching",
    choices: ["a: 3", "b: 4", "c: 5", "d: 6"],
    images: []
  },
  {
    id: "audio-mid-006",
    source: "音声工学 中間",
    category: "audio",
    number: 6,
    prompt: "輪状甲状筋が収縮すると、声帯と声はどうなるか。",
    answer: "声帯は膨張し、声は高くなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-007",
    source: "音声工学 中間",
    category: "audio",
    number: 7,
    prompt: "甲状披裂筋が収縮すると、声帯と声はどうなるか。",
    answer: "声帯は収縮し、声は低くなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-008",
    source: "音声工学 中間",
    category: "audio",
    number: 8,
    prompt: "人間が声の高さ（ピッチ）として知覚する物理量は主に何か。",
    answer: "声帯振動の基本周波数(f0)",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-009",
    source: "音声工学 中間",
    category: "audio",
    number: 9,
    prompt: "女性の声帯について、振動部分の長さ・質量・振幅・最高周波数を答えなさい。",
    answer: "長さ = 1 cm / 質量 = 1 g / 振幅 = 1 mm / 最高周波数 = 1 kHz",
    type: "matching",
    choices: ["a: 1 cm", "b: 1 g", "c: 1 mm", "d: 1 kHz"],
    images: []
  },
  {
    id: "audio-mid-010",
    source: "音声工学 中間",
    category: "audio",
    number: 10,
    prompt: "安静呼吸の吸気時に働く筋肉を答えなさい。",
    answer: "横隔膜 / 外肋間筋",
    type: "multiple",
    choices: ["横隔膜", "外肋間筋", "内肋間筋", "腹筋"],
    images: []
  },
  {
    id: "audio-mid-011",
    source: "音声工学 中間",
    category: "audio",
    number: 11,
    prompt: "腹式呼吸では、吸気時と呼気時にそれぞれ何が働くか。",
    answer: "吸気時 = 横隔膜 / 呼気時 = 腹筋",
    type: "matching",
    choices: ["a: 横隔膜", "b: 腹筋", "c: 外肋間筋", "d: 内肋間筋"],
    images: []
  },
  {
    id: "audio-mid-012",
    source: "音声工学 中間",
    category: "audio",
    number: 12,
    prompt: "象の鼻、イカの足、舌のように内部に骨がなく、ほとんどが筋組織からなる組織を何というか。",
    answer: "筋静水圧系",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-013",
    source: "音声工学 中間",
    category: "audio",
    number: 13,
    prompt: "舌の運動について、深層の筋群・浅層の筋群・螺旋状に走る浅層の筋群が収縮した時の動きを答えなさい。",
    answer: "深層の筋群 = 伸張 / 浅層の筋群 = 短縮 / 螺旋状の浅層筋群 = 回旋",
    type: "matching",
    choices: ["a: 伸張", "b: 短縮", "c: 回旋"],
    images: []
  },
  {
    id: "audio-mid-014",
    source: "音声工学 中間",
    category: "audio",
    number: 14,
    prompt: "自己相関係数を用いたピッチ抽出では、シフト量がピッチ周期と一致すると係数はどうなるか。",
    answer: "極大",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-015",
    source: "音声工学 中間",
    category: "audio",
    number: 15,
    prompt: "ケプストラムとは、一般的に音声の対数スペクトルを何したものか。",
    answer: "逆フーリエ変換",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-016",
    source: "音声工学 中間",
    category: "audio",
    number: 16,
    prompt: "ケプストラムの低次成分と高次成分には、それぞれ何の成分が含まれるか。",
    answer: "低次成分 = 声道共鳴 / 高次成分 = 声帯振動",
    type: "matching",
    choices: ["a: 声道共鳴", "b: 声帯振動"],
    images: []
  },
  {
    id: "audio-mid-017",
    source: "音声工学 中間",
    category: "audio",
    number: 17,
    prompt: "線形予測係数は、声道伝達関数を分子が1の何フィルタで表した時の分母の係数か。",
    answer: "IIR",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-018",
    source: "音声工学 中間",
    category: "audio",
    number: 18,
    prompt: "フォルマントとは、母音スペクトルのどの部分か。",
    answer: "山",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-019",
    source: "音声工学 中間",
    category: "audio",
    number: 19,
    prompt: "母音のF1周波数とF2周波数は、それぞれ舌のどの位置を反映するか。",
    answer: "F1 = 上下 / F2 = 前後",
    type: "matching",
    choices: ["a: 上下", "b: 前後"],
    images: []
  },
  {
    id: "audio-mid-020",
    source: "音声工学 中間",
    category: "audio",
    number: 20,
    prompt: "線形予測係数を用いた声道伝達関数の何の周波数が、フォルマントの中心周波数を表すか。",
    answer: "極",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-021",
    source: "音声工学 中間",
    category: "audio",
    number: 21,
    prompt: "/aiueo/を速く、またはあいまいに発話すると、F1-F2平面上の母音5角形の面積はどうなるか。",
    answer: "小さくなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-022",
    source: "音声工学 中間",
    category: "audio",
    number: 22,
    prompt: "母音5角形は、声道が小さくなると原点からどうなるか。",
    answer: "原点から遠ざかる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-023",
    source: "音声工学 中間",
    category: "audio",
    number: 23,
    prompt: "刺激が連続的であるにもかかわらず、知覚が範疇的に行われることを何というか。",
    answer: "カテゴリ知覚",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-024",
    source: "音声工学 中間",
    category: "audio",
    number: 24,
    prompt: "無声摩擦音 /s/ と /ʃ/、鼻音 /m/ と /n/ の違いは何に現れるか。",
    answer: "スペクトル",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-025",
    source: "音声工学 中間",
    category: "audio",
    number: 25,
    prompt: "破裂音の無声と有声の弁別の手がかりとなる物理量は何か。",
    answer: "VOT",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-026",
    source: "音声工学 中間",
    category: "audio",
    number: 26,
    prompt: "有声破裂音は、後続母音へのF2遷移パターンの違いにより特徴づけられる。この遷移パターンの仮想的な開始点を何というか。",
    answer: "ローカス",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-01-001",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 1,
    prompt: "音声と言語について、正しい組み合わせを答えなさい。\n（イ）は人間の発声器官を用いて発した音、（ロ）は思想・感情・意志などを伝達する記号体系である。",
    answer: "イ = 音声 / ロ = 言語",
    type: "matching",
    choices: ["a: 音声", "b: 言語", "c: 文字", "d: 音素"],
    images: []
  },
  {
    id: "audio-pred-01-002",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 2,
    prompt: "音声工学の主な変換技術について、TTSとSTTの説明を答えなさい。",
    answer: "TTS = 文字言語から音声言語へ変換 / STT = 音声言語から文字言語へ変換",
    type: "matching",
    choices: ["a: 文字言語から音声言語へ変換", "b: 音声言語から文字言語へ変換", "c: 音声から音声へ変換", "d: 文字から文字へ変換"],
    images: []
  },
  {
    id: "audio-pred-01-003",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 3,
    prompt: "語族とは何か。最も近い説明を選びなさい。",
    answer: "共通の祖語から派生した諸言語の総体",
    type: "single",
    choices: ["共通の祖語から派生した諸言語の総体", "文字の形が似ている言語の集合", "話者数が同じくらいの言語の集合", "文法だけが同じ言語の集合"],
    images: []
  },
  {
    id: "audio-pred-01-004",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 4,
    prompt: "日本語の特徴について、正しい組み合わせを答えなさい。",
    answer: "話者数 = 世界第9位 / 系統 = 不明の孤立した言語 / 語順 = SOV型 / 文字体系 = かな・カタカナ・漢字・英数文字を混用",
    type: "matching",
    choices: ["a: 世界第9位", "b: 不明の孤立した言語", "c: SOV型", "d: かな・カタカナ・漢字・英数文字を混用", "e: SVO型"],
    images: []
  },
  {
    id: "audio-pred-01-005",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 5,
    prompt: "文字体系について、音節文字・表語文字・表意文字の例を答えなさい。",
    answer: "音節文字 = かな / 表語文字 = 漢字 / 表意文字 = アラビア数字",
    type: "matching",
    choices: ["a: かな", "b: 漢字", "c: アラビア数字", "d: ラテン文字"],
    images: []
  },
  {
    id: "audio-pred-02-001",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 1,
    prompt: "声道を構成する4つの腔をすべて選びなさい。",
    answer: "喉頭腔 / 咽頭腔 / 口腔 / 鼻腔",
    type: "multiple",
    choices: ["喉頭腔", "咽頭腔", "口腔", "鼻腔", "肺胞"],
    images: []
  },
  {
    id: "audio-pred-02-002",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 2,
    prompt: "母音と子音について、正しい説明を答えなさい。",
    answer: "母音 = 声帯振動を音源とし顕著な狭めを持たない言語音 / 子音 = 母音以外の言語音",
    type: "matching",
    choices: ["a: 声帯振動を音源とし顕著な狭めを持たない言語音", "b: 母音以外の言語音", "c: 意味を持つ発音のまとまり", "d: 文字で表した音"],
    images: []
  },
  {
    id: "audio-pred-02-003",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 3,
    prompt: "日本語の音素 /h/ の異音について、「は」「ひ」「ふ」の頭子音の種類を答えなさい。",
    answer: "は = 無声声門摩擦音 / ひ = 無声硬口蓋摩擦音 / ふ = 無声両唇摩擦音",
    type: "matching",
    choices: ["a: 無声声門摩擦音", "b: 無声硬口蓋摩擦音", "c: 無声両唇摩擦音", "d: 無声歯茎摩擦音"],
    images: []
  },
  {
    id: "audio-pred-02-004",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 4,
    prompt: "音素表記では、音素記号を何で前後から挟むか。",
    answer: "/ /",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-02-005",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 5,
    prompt: "音節とモーラについて、正しい説明を答えなさい。",
    answer: "音節 = 0個以上のC + 1個のV + 0個以上のC / モーラ = 0〜2個のC + 1個のV、または特殊モーラ",
    type: "matching",
    choices: ["a: 0個以上のC + 1個のV + 0個以上のC", "b: 0〜2個のC + 1個のV、または特殊モーラ", "c: 意味を持つ発音のまとまり", "d: 声の高さの単位"],
    images: []
  },
  {
    id: "audio-pred-03-001",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 1,
    prompt: "喉頭の構造で覚えるべき骨1つと軟骨3つを答えなさい。",
    answer: "骨 = 舌骨 / 軟骨 = 甲状軟骨・輪状軟骨・披裂軟骨",
    type: "matching",
    choices: ["a: 舌骨", "b: 甲状軟骨・輪状軟骨・披裂軟骨", "c: 下顎骨", "d: 口蓋骨・鼻骨・頬骨"],
    images: []
  },
  {
    id: "audio-pred-03-002",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 2,
    prompt: "声門とは何か。",
    answer: "左右の声帯の隙間",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-03-003",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 3,
    prompt: "喉頭の筋肉と作用について、正しい組み合わせを答えなさい。",
    answer: "後輪状披裂筋 = 声門開放 / 外側輪状披裂筋 = 声門閉鎖 / 横披裂筋 = 声門閉鎖 / 輪状甲状筋 = 声帯を伸ばす",
    type: "matching",
    choices: ["a: 声門開放", "b: 声門閉鎖", "c: 声帯を伸ばす", "d: 声帯を縮める"],
    images: []
  },
  {
    id: "audio-pred-03-004",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 4,
    prompt: "声帯筋・甲状披裂筋（TA）は声帯にどのように作用するか。",
    answer: "声帯を縮める",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-03-005",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 5,
    prompt: "ピッチとして知覚される主な物理量と、声帯振動がない場合の知覚について答えなさい。",
    answer: "主な物理量 = 声帯振動の基本周波数 / 声帯振動がない場合 = ピッチ感なし",
    type: "matching",
    choices: ["a: 声帯振動の基本周波数", "b: ピッチ感なし", "c: 音圧レベル", "d: 声道長"],
    images: []
  },
  {
    id: "audio-pred-04-001",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 1,
    prompt: "ヒトの声道は、口腔から咽頭腔にかけて約何度に屈曲しているか。",
    answer: "90度",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-04-002",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 2,
    prompt: "肺の構造について、左右の葉の数を答えなさい。",
    answer: "右 = 三葉 / 左 = 二葉",
    type: "matching",
    choices: ["a: 三葉", "b: 二葉", "c: 一葉", "d: 四葉"],
    images: []
  },
  {
    id: "audio-pred-04-003",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 3,
    prompt: "呼吸様式と働く筋について、正しい組み合わせを答えなさい。",
    answer: "安静呼吸の吸気 = 外肋間筋・横隔膜 / 胸式深呼吸の呼気 = 内肋間筋 / 腹式深呼吸の呼気 = 腹筋",
    type: "matching",
    choices: ["a: 外肋間筋・横隔膜", "b: 内肋間筋", "c: 腹筋", "d: 声帯筋"],
    images: []
  },
  {
    id: "audio-pred-04-004",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 4,
    prompt: "発話時、軟口蓋はどのように動き、何を閉鎖するか。",
    answer: "挙上し、鼻腔への入り口を閉鎖する",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-04-005",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 5,
    prompt: "鼻腔・副鼻腔について、鼻腔を左右に二分するものと、周囲の骨の中の空間を答えなさい。",
    answer: "左右に二分するもの = 鼻中隔 / 周囲の骨の中の空間 = 副鼻腔",
    type: "matching",
    choices: ["a: 鼻中隔", "b: 副鼻腔", "c: 口蓋垂", "d: 舌骨"],
    images: []
  },
  {
    id: "audio-pred-05-001",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 1,
    prompt: "音の3属性と、それに対応する物理的特徴を答えなさい。",
    answer: "大きさ = 音圧 / 高さ = 基本周波数 / 音色 = スペクトル",
    type: "matching",
    choices: ["a: 音圧", "b: 基本周波数", "c: スペクトル", "d: 声道長"],
    images: []
  },
  {
    id: "audio-pred-05-002",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 2,
    prompt: "最小可聴音圧値はいくらか。単位付きで答えなさい。",
    answer: "2 × 10^-5 Pa",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-05-003",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 3,
    prompt: "通常の会話の音圧レベルはおよそ何dBか。",
    answer: "60 dB",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-05-004",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 4,
    prompt: "代表的なピッチ抽出法について、処理の種類と方法の組み合わせを答えなさい。",
    answer: "波形処理 = 零交叉法 / 相関処理 = 自己相関法・AMDF法 / スペクトル処理 = ケプストラム",
    type: "matching",
    choices: ["a: 零交叉法", "b: 自己相関法・AMDF法", "c: ケプストラム", "d: LPC"],
    images: []
  },
  {
    id: "audio-pred-05-005",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 5,
    prompt: "自己相関法で、シフト量kが音声信号の周期に一致すると自己相関係数はどうなるか。",
    answer: "極大になる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-06-001",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 1,
    prompt: "フォルマントについて、正しい説明を答えなさい。",
    answer: "音声スペクトルの山で、声道の共鳴に由来する",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-06-002",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 2,
    prompt: "母音5角形について、F1・F2と舌の位置の対応を答えなさい。",
    answer: "F1 = 舌の上下位置 / F2 = 舌の前後位置",
    type: "matching",
    choices: ["a: 舌の上下位置", "b: 舌の前後位置", "c: 声帯の開閉", "d: 口唇の丸め"],
    images: []
  },
  {
    id: "audio-pred-06-003",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 3,
    prompt: "日本語5母音は、ほぼどのフォルマントだけで弁別可能か。",
    answer: "F1とF2",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-06-004",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 4,
    prompt: "無声摩擦音 /s/ と /ʃ/ のスペクトルの違いについて、正しい組み合わせを答えなさい。",
    answer: "/s/ = 6 kHz以上にピーク / /ʃ/ = 4 kHz付近にピーク",
    type: "matching",
    choices: ["a: 6 kHz以上にピーク", "b: 4 kHz付近にピーク", "c: 1 kHz付近にピーク", "d: ピークを持たない"],
    images: []
  },
  {
    id: "audio-pred-06-005",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 5,
    prompt: "有声摩擦音では、摩擦音のスペクトルに何が重畳するか。",
    answer: "声帯振動の倍音成分や声道共鳴",
    type: "text",
    choices: [],
    images: []
  }
];
