window.STUDY_EXTRA_QUESTION_DATA = [
  {
    id: "audio-mid-001",
    source: "音声工学 中間",
    category: "audio",
    number: 1,
    prompt: "日本語について、次の空欄に入る組み合わせを答えなさい。\n日本語は世界で（イ）番目に話者数が多いが、系統が（ロ）孤立した言語である。基礎語彙や（ハ）体系はオーストロネシア語族に由来、（ニ）体系はアルタイ諸語に由来すると言われている。",
    answer: "イ = 9 / ロ = 不明な / ハ = 音韻 / ニ = 文法",
    type: "matching",
    choices: ["a: 90", "b: 9", "c: 明らかな", "d: 不明な", "e: 文法", "f: 音韻"],
    images: []
  },
  {
    id: "audio-mid-002",
    source: "音声工学 中間",
    category: "audio",
    number: 2,
    prompt: "音が発生する3つの原因と音声での対応について、正しい組み合わせを答えなさい。\n（イ）物体の振動、（ロ）空気の乱流、（ハ）空気の急激な膨張や収縮。",
    answer: "イ = 母音 / ロ = 摩擦音 / ハ = 破裂音",
    type: "matching",
    choices: ["a: 母音", "b: 摩擦音", "c: 破裂音"],
    images: []
  },
  {
    id: "audio-mid-003",
    source: "音声工学 中間",
    category: "audio",
    number: 3,
    prompt: "「ぴ」の頭子音を有声化した仮名を書きなさい。",
    answer: "び",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-004",
    source: "音声工学 中間",
    category: "audio",
    number: 4,
    prompt: "あらゆる言語の音声を文字で表記するために、国際音声学会が定めた記号を3文字のアルファベットで答えなさい。",
    answer: "IPA",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-005",
    source: "音声工学 中間",
    category: "audio",
    number: 5,
    prompt: "次の語はそれぞれ何モーラか答えなさい。",
    answer: "東京都 = 5 / チョコレート = 5 / 関東 = 4 / サッカー = 4",
    type: "matching",
    choices: ["a: 3", "b: 4", "c: 5", "d: 6"],
    images: []
  },
  {
    id: "audio-mid-006",
    source: "音声工学 中間",
    category: "audio",
    number: 6,
    prompt: "輪状甲状筋が収縮すると、声帯と声はどうなるか。",
    answer: "声帯は膨張し、声は高くなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-007",
    source: "音声工学 中間",
    category: "audio",
    number: 7,
    prompt: "甲状披裂筋が収縮すると、声帯と声はどうなるか。",
    answer: "声帯は収縮し、声は低くなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-008",
    source: "音声工学 中間",
    category: "audio",
    number: 8,
    prompt: "人間が声の高さ（ピッチ）として知覚する物理量は主に何か。",
    answer: "声帯振動の基本周波数(f0)",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-009",
    source: "音声工学 中間",
    category: "audio",
    number: 9,
    prompt: "女性の声帯について、振動部分の長さ・質量・振幅・最高周波数を答えなさい。",
    answer: "長さ = 1 cm / 質量 = 1 g / 振幅 = 1 mm / 最高周波数 = 1 kHz",
    type: "matching",
    choices: ["a: 1 cm", "b: 1 g", "c: 1 mm", "d: 1 kHz"],
    images: []
  },
  {
    id: "audio-mid-010",
    source: "音声工学 中間",
    category: "audio",
    number: 10,
    prompt: "安静呼吸の吸気時に働く筋肉を答えなさい。",
    answer: "横隔膜 / 外肋間筋",
    type: "multiple",
    choices: ["横隔膜", "外肋間筋", "内肋間筋", "腹筋"],
    images: []
  },
  {
    id: "audio-mid-011",
    source: "音声工学 中間",
    category: "audio",
    number: 11,
    prompt: "腹式呼吸では、吸気時と呼気時にそれぞれ何が働くか。",
    answer: "吸気時 = 横隔膜 / 呼気時 = 腹筋",
    type: "matching",
    choices: ["a: 横隔膜", "b: 腹筋", "c: 外肋間筋", "d: 内肋間筋"],
    images: []
  },
  {
    id: "audio-mid-012",
    source: "音声工学 中間",
    category: "audio",
    number: 12,
    prompt: "象の鼻、イカの足、舌のように内部に骨がなく、ほとんどが筋組織からなる組織を何というか。",
    answer: "筋静水圧系",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-013",
    source: "音声工学 中間",
    category: "audio",
    number: 13,
    prompt: "舌の運動について、深層の筋群・浅層の筋群・螺旋状に走る浅層の筋群が収縮した時の動きを答えなさい。",
    answer: "深層の筋群 = 伸張 / 浅層の筋群 = 短縮 / 螺旋状の浅層筋群 = 回旋",
    type: "matching",
    choices: ["a: 伸張", "b: 短縮", "c: 回旋"],
    images: []
  },
  {
    id: "audio-mid-014",
    source: "音声工学 中間",
    category: "audio",
    number: 14,
    prompt: "自己相関係数を用いたピッチ抽出では、シフト量がピッチ周期と一致すると係数はどうなるか。",
    answer: "極大",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-015",
    source: "音声工学 中間",
    category: "audio",
    number: 15,
    prompt: "ケプストラムとは、一般的に音声の対数スペクトルを何したものか。",
    answer: "逆フーリエ変換",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-mid-016",
    source: "音声工学 中間",
    category: "audio",
    number: 16,
    prompt: "ケプストラムの低次成分と高次成分には、それぞれ何の成分が含まれるか。",
    answer: "低次成分 = 声道共鳴 / 高次成分 = 声帯振動",
    type: "matching",
    choices: ["a: 声道共鳴", "b: 声帯振動"],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-mid-017",
    source: "音声工学 中間",
    category: "audio",
    number: 17,
    prompt: "線形予測係数は、声道伝達関数を分子が1の何フィルタで表した時の分母の係数か。",
    answer: "IIR",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-mid-018",
    source: "音声工学 中間",
    category: "audio",
    number: 18,
    prompt: "フォルマントとは、母音スペクトルのどの部分か。",
    answer: "山",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-mid-019",
    source: "音声工学 中間",
    category: "audio",
    number: 19,
    prompt: "母音のF1周波数とF2周波数は、それぞれ舌のどの位置を反映するか。",
    answer: "F1 = 上下 / F2 = 前後",
    type: "matching",
    choices: ["a: 上下", "b: 前後"],
    images: []
  },
  {
    id: "audio-mid-020",
    source: "音声工学 中間",
    category: "audio",
    number: 20,
    prompt: "線形予測係数を用いた声道伝達関数の何の周波数が、フォルマントの中心周波数を表すか。",
    answer: "極",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-mid-021",
    source: "音声工学 中間",
    category: "audio",
    number: 21,
    prompt: "/aiueo/を速く、またはあいまいに発話すると、F1-F2平面上の母音5角形の面積はどうなるか。",
    answer: "小さくなる",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-vowel-pentagon.svg"]
  },
  {
    id: "audio-mid-022",
    source: "音声工学 中間",
    category: "audio",
    number: 22,
    prompt: "母音5角形は、声道が小さくなると原点からどうなるか。",
    answer: "原点から遠ざかる",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-vowel-pentagon.svg"]
  },
  {
    id: "audio-mid-023",
    source: "音声工学 中間",
    category: "audio",
    number: 23,
    prompt: "刺激が連続的であるにもかかわらず、知覚が範疇的に行われることを何というか。",
    answer: "カテゴリ知覚",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-024",
    source: "音声工学 中間",
    category: "audio",
    number: 24,
    prompt: "無声摩擦音 /s/ と /ʃ/、鼻音 /m/ と /n/ の違いは何に現れるか。",
    answer: "スペクトル",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-mid-025",
    source: "音声工学 中間",
    category: "audio",
    number: 25,
    prompt: "破裂音の無声と有声の弁別の手がかりとなる物理量は何か。",
    answer: "VOT",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-026",
    source: "音声工学 中間",
    category: "audio",
    number: 26,
    prompt: "有声破裂音は、後続母音へのF2遷移パターンの違いにより特徴づけられる。この遷移パターンの仮想的な開始点を何というか。",
    answer: "ローカス",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-01-001",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 1,
    prompt: "音声と言語について、正しい組み合わせを答えなさい。\n（イ）は人間の発声器官を用いて発した音、（ロ）は思想・感情・意志などを伝達する記号体系である。",
    answer: "イ = 音声 / ロ = 言語",
    type: "matching",
    choices: ["a: 音声", "b: 言語", "c: 文字", "d: 音素"],
    images: []
  },
  {
    id: "audio-pred-01-002",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 2,
    prompt: "音声工学の主な変換技術について、TTSとSTTの説明を答えなさい。",
    answer: "TTS = 文字言語から音声言語へ変換 / STT = 音声言語から文字言語へ変換",
    type: "matching",
    choices: ["a: 文字言語から音声言語へ変換", "b: 音声言語から文字言語へ変換", "c: 音声から音声へ変換", "d: 文字から文字へ変換"],
    images: []
  },
  {
    id: "audio-pred-01-003",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 3,
    prompt: "語族とは何か。最も近い説明を選びなさい。",
    answer: "共通の祖語から派生した諸言語の総体",
    type: "single",
    choices: ["共通の祖語から派生した諸言語の総体", "文字の形が似ている言語の集合", "話者数が同じくらいの言語の集合", "文法だけが同じ言語の集合"],
    images: []
  },
  {
    id: "audio-pred-01-004",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 4,
    prompt: "日本語の特徴について、正しい組み合わせを答えなさい。",
    answer: "話者数 = 世界第9位 / 系統 = 不明の孤立した言語 / 語順 = SOV型 / 文字体系 = かな・カタカナ・漢字・英数文字を混用",
    type: "matching",
    choices: ["a: 世界第9位", "b: 不明の孤立した言語", "c: SOV型", "d: かな・カタカナ・漢字・英数文字を混用", "e: SVO型"],
    images: []
  },
  {
    id: "audio-pred-01-005",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 5,
    prompt: "文字体系について、音節文字・表語文字・表意文字の例を答えなさい。",
    answer: "音節文字 = かな / 表語文字 = 漢字 / 表意文字 = アラビア数字",
    type: "matching",
    choices: ["a: かな", "b: 漢字", "c: アラビア数字", "d: ラテン文字"],
    images: []
  },
  {
    id: "audio-pred-02-001",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 1,
    prompt: "声道を構成する4つの腔をすべて選びなさい。",
    answer: "喉頭腔 / 咽頭腔 / 口腔 / 鼻腔",
    type: "multiple",
    choices: ["喉頭腔", "咽頭腔", "口腔", "鼻腔", "肺胞"],
    images: ["assets/ref-audio-vocal-tract.svg"]
  },
  {
    id: "audio-pred-02-002",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 2,
    prompt: "母音と子音について、正しい説明を答えなさい。",
    answer: "母音 = 声帯振動を音源とし顕著な狭めを持たない言語音 / 子音 = 母音以外の言語音",
    type: "matching",
    choices: ["a: 声帯振動を音源とし顕著な狭めを持たない言語音", "b: 母音以外の言語音", "c: 意味を持つ発音のまとまり", "d: 文字で表した音"],
    images: []
  },
  {
    id: "audio-pred-02-003",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 3,
    prompt: "日本語の音素 /h/ の異音について、「は」「ひ」「ふ」の頭子音の種類を答えなさい。",
    answer: "は = 無声声門摩擦音 / ひ = 無声硬口蓋摩擦音 / ふ = 無声両唇摩擦音",
    type: "matching",
    choices: ["a: 無声声門摩擦音", "b: 無声硬口蓋摩擦音", "c: 無声両唇摩擦音", "d: 無声歯茎摩擦音"],
    images: []
  },
  {
    id: "audio-pred-02-004",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 4,
    prompt: "音素表記では、音素記号を何で前後から挟むか。",
    answer: "/ /",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-02-005",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 5,
    prompt: "音節とモーラについて、正しい説明を答えなさい。",
    answer: "音節 = 0個以上のC + 1個のV + 0個以上のC / モーラ = 0〜2個のC + 1個のV、または特殊モーラ",
    type: "matching",
    choices: ["a: 0個以上のC + 1個のV + 0個以上のC", "b: 0〜2個のC + 1個のV、または特殊モーラ", "c: 意味を持つ発音のまとまり", "d: 声の高さの単位"],
    images: []
  },
  {
    id: "audio-pred-03-001",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 1,
    prompt: "喉頭の構造で覚えるべき骨1つと軟骨3つを答えなさい。",
    answer: "骨 = 舌骨 / 軟骨 = 甲状軟骨・輪状軟骨・披裂軟骨",
    type: "matching",
    choices: ["a: 舌骨", "b: 甲状軟骨・輪状軟骨・披裂軟骨", "c: 下顎骨", "d: 口蓋骨・鼻骨・頬骨"],
    images: ["assets/ref-audio-larynx-test-redacted.png"]
  },
  {
    id: "audio-pred-03-002",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 2,
    prompt: "声門とは何か。",
    answer: "左右の声帯の隙間",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-03-003",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 3,
    prompt: "喉頭の筋肉と作用について、正しい組み合わせを答えなさい。",
    answer: "後輪状披裂筋 = 声門開放 / 外側輪状披裂筋 = 声門閉鎖 / 横披裂筋 = 声門閉鎖 / 輪状甲状筋 = 声帯を伸ばす",
    type: "matching",
    choices: ["a: 声門開放", "b: 声門閉鎖", "c: 声帯を伸ばす", "d: 声帯を縮める"],
    images: []
  },
  {
    id: "audio-pred-03-004",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 4,
    prompt: "声帯筋・甲状披裂筋（TA）は声帯にどのように作用するか。",
    answer: "声帯を縮める",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-03-005",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 5,
    prompt: "ピッチとして知覚される主な物理量と、声帯振動がない場合の知覚について答えなさい。",
    answer: "主な物理量 = 声帯振動の基本周波数 / 声帯振動がない場合 = ピッチ感なし",
    type: "matching",
    choices: ["a: 声帯振動の基本周波数", "b: ピッチ感なし", "c: 音圧レベル", "d: 声道長"],
    images: []
  },
  {
    id: "audio-pred-04-001",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 1,
    prompt: "ヒトの声道は、口腔から咽頭腔にかけて約何度に屈曲しているか。",
    answer: "90度",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-vocal-tract.svg"]
  },
  {
    id: "audio-pred-04-002",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 2,
    prompt: "肺の構造について、左右の葉の数を答えなさい。",
    answer: "右 = 三葉 / 左 = 二葉",
    type: "matching",
    choices: ["a: 三葉", "b: 二葉", "c: 一葉", "d: 四葉"],
    images: []
  },
  {
    id: "audio-pred-04-003",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 3,
    prompt: "呼吸様式と働く筋について、正しい組み合わせを答えなさい。",
    answer: "安静呼吸の吸気 = 外肋間筋・横隔膜 / 胸式深呼吸の呼気 = 内肋間筋 / 腹式深呼吸の呼気 = 腹筋",
    type: "matching",
    choices: ["a: 外肋間筋・横隔膜", "b: 内肋間筋", "c: 腹筋", "d: 声帯筋"],
    images: []
  },
  {
    id: "audio-pred-04-004",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 4,
    prompt: "発話時、軟口蓋はどのように動き、何を閉鎖するか。",
    answer: "挙上し、鼻腔への入り口を閉鎖する",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-04-005",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 5,
    prompt: "鼻腔・副鼻腔について、鼻腔を左右に二分するものと、周囲の骨の中の空間を答えなさい。",
    answer: "左右に二分するもの = 鼻中隔 / 周囲の骨の中の空間 = 副鼻腔",
    type: "matching",
    choices: ["a: 鼻中隔", "b: 副鼻腔", "c: 口蓋垂", "d: 舌骨"],
    images: []
  },
  {
    id: "audio-pred-05-001",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 1,
    prompt: "音の3属性と、それに対応する物理的特徴を答えなさい。",
    answer: "大きさ = 音圧 / 高さ = 基本周波数 / 音色 = スペクトル",
    type: "matching",
    choices: ["a: 音圧", "b: 基本周波数", "c: スペクトル", "d: 声道長"],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-pred-05-002",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 2,
    prompt: "最小可聴音圧値はいくらか。単位付きで答えなさい。",
    answer: "2 × 10^-5 Pa",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-05-003",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 3,
    prompt: "通常の会話の音圧レベルはおよそ何dBか。",
    answer: "60 dB",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-05-004",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 4,
    prompt: "代表的なピッチ抽出法について、処理の種類と方法の組み合わせを答えなさい。",
    answer: "波形処理 = 零交叉法 / 相関処理 = 自己相関法・AMDF法 / スペクトル処理 = ケプストラム",
    type: "matching",
    choices: ["a: 零交叉法", "b: 自己相関法・AMDF法", "c: ケプストラム", "d: LPC"],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-pred-05-005",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 5,
    prompt: "自己相関法で、シフト量kが音声信号の周期に一致すると自己相関係数はどうなるか。",
    answer: "極大になる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-06-001",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 1,
    prompt: "フォルマントについて、正しい説明を答えなさい。",
    answer: "音声スペクトルの山で、声道の共鳴に由来する",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-pred-06-002",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 2,
    prompt: "母音5角形について、F1・F2と舌の位置の対応を答えなさい。",
    answer: "F1 = 舌の上下位置 / F2 = 舌の前後位置",
    type: "matching",
    choices: ["a: 舌の上下位置", "b: 舌の前後位置", "c: 声帯の開閉", "d: 口唇の丸め"],
    images: ["assets/ref-audio-vowel-pentagon.svg"]
  },
  {
    id: "audio-pred-06-003",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 3,
    prompt: "日本語5母音は、ほぼどのフォルマントだけで弁別可能か。",
    answer: "F1とF2",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-vowel-pentagon.svg"]
  },
  {
    id: "audio-pred-06-004",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 4,
    prompt: "無声摩擦音 /s/ と /ʃ/ のスペクトルの違いについて、正しい組み合わせを答えなさい。",
    answer: "s音 = 6 kHz以上にピーク / sh音 = 4 kHz付近にピーク",
    type: "matching",
    choices: ["a: 6 kHz以上にピーク", "b: 4 kHz付近にピーク", "c: 1 kHz付近にピーク", "d: ピークを持たない"],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "audio-pred-06-005",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 5,
    prompt: "有声摩擦音では、摩擦音のスペクトルに何が重畳するか。",
    answer: "声帯振動の倍音成分や声道共鳴",
    type: "text",
    choices: [],
    images: ["assets/ref-audio-spectrum-cepstrum.svg"]
  },
  {
    id: "knowledge-mid-001",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 1,
    prompt: "人工知能を表すAIとは何という英単語の略か。2スペルアウトして答えなさい。",
    answer: "artificial intelligence",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-002",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 2,
    prompt: "人工知能で何か新しいことが実現され、その原理が分かってしまうと「それは知能ではない」と思ってしまう人間心理を何というか。",
    answer: "AI効果",
    type: "single",
    choices: ["R2D2効果", "AI効果", "イライザ効果", "ピグマリオン効果", "バンドワゴン効果"],
    images: []
  },
  {
    id: "knowledge-mid-003",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 3,
    prompt: "探索問題などの問題解決において、到達可能で考察の対象となる状況全ての集合を何というか。",
    answer: "状態空間",
    type: "single",
    choices: ["指数集合", "目標状態", "組合せ爆発", "指数関数", "初期状態", "状態空間"],
    images: []
  },
  {
    id: "knowledge-mid-004",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 4,
    prompt: "Rで次の行列Bが定義されている。\nB = [1 0 2; 2 0 1]\nB[2, 1] の実行結果を答えなさい。",
    answer: "2",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-005",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 5,
    prompt: "Rで次の行列Aが定義されている。\nA = [0 3 0 1; 1 2 0 2; 1 1 1 1; 2 2 3 3; 1 0 1 0; 0 1 0 1]\nmax(A[, 2]) の実行結果を答えなさい。",
    answer: "3",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-006",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 6,
    prompt: "Rで次の行列Bが定義されている。\nB = [1 0 2; 2 0 1]\nmean(B[1, ]) の実行結果を答えなさい。",
    answer: "1",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-007",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 7,
    prompt: "Rで次の行列Aが定義されている。\nA = [0 3 0 1; 1 2 0 2; 1 1 1 1; 2 2 3 3; 1 0 1 0; 0 1 0 1]\njyo=(A[,1]>=1); max(A[jyo, 2]) の実行結果を答えなさい。",
    answer: "2",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-008",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 8,
    prompt: "予測モデルA y = 2800x1 + 170x2 - 10500x3 + 350 を用いる。平均気温x1=25、平均湿度x2=70、曜日x3=0のとき、電力需要量yを求めなさい。",
    answer: "82250",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-009",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 9,
    prompt: "予測モデルBは次の決定木である。\n最初にx1<26なら左、x1>=26なら右へ進む。左側はx3=0ならx2で分岐し、x2<65なら69000、x2>=65なら75000、x3=1なら80000。右側はx1<30ならx2で分岐し、x2<70なら90000、x2>=70なら130000、x1>=30なら145000。\nx1=29、x2=80、x3=0のとき、電力需要量を求めなさい。",
    answer: "130000",
    type: "text",
    choices: [],
    images: ["assets/ref-knowledge-electricity-tree.svg"]
  },
  {
    id: "knowledge-mid-010",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 10,
    prompt: "予測モデルAは重回帰式、予測モデルBは木構造で連続値を予測するモデルである。予測モデルBを何と呼ぶか。",
    answer: "回帰木",
    type: "single",
    choices: ["判別木", "ニューラルネットワーク", "深層学習", "回帰木", "クラスタリング", "決定木", "パーセプトロン"],
    images: ["assets/ref-knowledge-electricity-tree.svg"]
  },
  {
    id: "knowledge-mid-011",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 11,
    prompt: "手順に従ってあらかじめ用意された処理をするだけのチャットボットプログラムは何と呼ばれるか。また、本物の人間と話していると錯覚することを何効果というか。",
    answer: "オ = 人工無脳 / カ = イライザ効果",
    type: "matching",
    choices: ["a: 人工無脳", "b: 人工知能", "c: チャットワーク", "d: 機械学習", "e: ディープラーニング", "f: イライザ効果", "g: チューリング", "h: エニアック"],
    images: []
  },
  {
    id: "knowledge-mid-012",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 12,
    prompt: "2012年、画像認識競技会ILSVRCで、カナダのトロント大学教授である（ウ）が率いるSuperVisionが圧勝した。これが現代AIにおける（エ）ブームの火付け役となった。",
    answer: "ウ = ジェフリー・ヒントン / エ = ディープラーニング",
    type: "matching",
    choices: ["a: マーヴィン・ミンスキー", "b: ジョン・マッカーシー", "c: フランキ・サイワ", "d: ジェフリー・ヒントン", "e: アラン・チューリング", "f: パーセプトロン", "g: 機械学習", "h: ディープラーニング", "i: IT"],
    images: ["assets/ref-knowledge-neural.svg"]
  },
  {
    id: "knowledge-mid-013",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 13,
    prompt: "別の場所にいる人間がコンピュータと会話し、相手がコンピュータと見抜けなければコンピュータには人間と同等な知能があると考える評価法を何というか。",
    answer: "チューリングテスト",
    type: "single",
    choices: ["中国語の部屋", "微分の部屋", "AI評価", "チューリングテスト", "りんなテスト", "AI効果"],
    images: []
  },
  {
    id: "knowledge-mid-014",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 14,
    prompt: "「AI自身が、今しようとしていることに関係のあることがらだけを選び出すことは非常に難しい」ことを表すAI分野の難問を何というか。",
    answer: "フレーム問題",
    type: "single",
    choices: ["フレーム問題", "身体性", "特徴量設計", "中国語の部屋", "シンギュラリティ"],
    images: []
  },
  {
    id: "knowledge-mid-015",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 15,
    prompt: "スライドで示されたボードゲームの状態空間の大きさについて、大きい順に並べなさい。",
    answer: "1 = 将棋 / 2 = 囲碁 / 3 = チェス / 4 = オセロ",
    type: "matching",
    choices: ["a: 将棋", "b: 囲碁", "c: チェス", "d: オセロ"],
    images: []
  },
  {
    id: "knowledge-mid-016",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 16,
    prompt: "機械学習では学習に利用できる（ア）が多ければ多いほど望ましい学習結果が得られる。（イ）の発展とともに利用可能な（ア）の種類と量が爆発的に増加した。",
    answer: "ア = データ / イ = インターネット",
    type: "matching",
    choices: ["a: コンピュータ", "b: サーバ", "c: 通信容量", "d: データ", "e: モデル", "f: ネットカフェ", "g: 検索エンジン", "h: データセンター", "i: インターネット", "j: クラウドコンピューティング", "k: ネットカフェ難民", "l: 通信帯域"],
    images: []
  },
  {
    id: "knowledge-mid-017",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 17,
    prompt: "2変数関数 z = 3x^2 - 5y^3 + x - y^2 + 3 の偏導関数 ∂z/∂y として適切なものを選びなさい。",
    answer: "-15y^2 - 2y",
    type: "single",
    choices: ["6x - 5y^3 + 1 - y^2", "-15y^2 - 2y + 6x", "6x + 1", "-15y^2 - 2y", "-15y^2 - 2y + 6x + 3", "6x - 15y^2 + 1 - 2y"],
    images: []
  },
  {
    id: "knowledge-mid-018",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 18,
    prompt: "ジョン・サールは、人間と同等に本物の心を持つ人工知能を（ス）と呼び、これは実現不可能であると主張した。サールは（セ）という思考実験を通じて主張を説明した。",
    answer: "ス = 強い人工知能 / セ = 中国語の部屋",
    type: "matching",
    choices: ["a: 特化型人工知能", "b: 汎用人工知能", "c: 弱い人工知能", "d: 強い人工知能", "e: 汎用テスト", "f: 中国語の部屋", "g: 微子の部屋", "h: 英語の部屋", "i: チューリングテスト", "j: 期末テスト"],
    images: []
  },
  {
    id: "knowledge-mid-019",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 19,
    prompt: "ニューラルネットワークの教師あり学習では、どのアルゴリズムが広く利用されているか。",
    answer: "誤差逆伝播法",
    type: "single",
    choices: ["最尤法", "誤差逆伝播法", "ID3アルゴリズム", "誤差伝搬法", "最小二乗法"],
    images: ["assets/ref-knowledge-neural.svg"]
  },
  {
    id: "knowledge-mid-020",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 20,
    prompt: "次の行列が定義されている。\nA = [0 3; 1 2], B = [1 0; 0 2]\nA + B = [a b; c d] としたとき、aに当てはまる値を選びなさい。",
    answer: "a = 1",
    type: "single",
    choices: ["a = 3", "a = 2", "a = 1", "a = 0", "a = 4"],
    images: []
  },
  {
    id: "knowledge-mid-021",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 21,
    prompt: "次の行列が定義されている。\nA = [0 3; 1 2], B = [1 0; 0 2]\nAB = [a b; c d] としたとき、cに当てはまる値を選びなさい。",
    answer: "c = 1",
    type: "single",
    choices: ["c = 6", "c = 3", "c = 0", "c = 1", "c = 2", "c = 5", "c = 4"],
    images: []
  },
  {
    id: "knowledge-mid-022",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 22,
    prompt: "「人工知能」という言葉は1956年にアメリカで開催された（キ）において、著名なアメリカ人工知能科学者（ク）によって初めて使われた。",
    answer: "キ = ダートマス会議 / ク = ジョン・マッカーシー",
    type: "matching",
    choices: ["a: AI会議", "b: ダートマス会議", "c: AAAI", "d: ボストン会議", "e: ダボス会議", "f: フランキ・サイワ", "g: ジョン・マッカーシー", "h: ジェフリー・ヒントン", "i: クロード・シャノン", "j: マーヴィン・ミンスキー"],
    images: []
  },
  {
    id: "knowledge-mid-023",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 23,
    prompt: "データを表す変数 x1, x2, x3 を用いて変数 y の値を求める線形回帰式 y = a1x1 + a2x2 + a3x3 + b が得られた。このとき、x1, x2, x3を何と呼び、yを何と呼ぶか。",
    answer: "ケ = 説明変数 / コ = 目的変数",
    type: "matching",
    choices: ["a: 切片", "b: 偏回帰係数", "c: 傾き", "d: 決定係数", "e: 説明変数", "f: 目的変数"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "knowledge-mid-024",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 24,
    prompt: "米国の思想家レイ・カーツワイルが主張する人工知能におけるシンギュラリティとは何か。要点を説明しなさい。",
    answer: "人工知能が十分に賢くなり、自分自身より賢い人工知能を作れるようになって、技術開発速度が爆発的に加速し、人間の想像を超える知性が生まれるという仮説。",
    type: "free",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-025",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 25,
    prompt: "ジョン・サールがチューリングテストを批判した理由を説明しなさい。",
    answer: "外から会話が成立しているように見えても、内部では記号を手順通り処理しているだけで意味を理解しているとは限らないため。中国語の部屋の思考実験でこの点を示した。",
    type: "free",
    choices: [],
    images: []
  },
  {
    id: "knowledge-pred-01-001",
    source: "知識工学 予想 第01回",
    category: "knowledge-prediction",
    number: 1,
    prompt: "知識工学とは何か。スライドの説明に合うように答えなさい。",
    answer: "人間の知識をコンピュータシステムに埋め込むことで、より高い機能や保守性を実現し、役立つシステムを作る工学分野。",
    type: "free",
    choices: [],
    images: []
  },
  {
    id: "knowledge-pred-01-002",
    source: "知識工学 予想 第01回",
    category: "knowledge-prediction",
    number: 2,
    prompt: "人工知能のレベル分類について、正しい組み合わせを答えなさい。",
    answer: "レベル1 = シンプルな制御 / レベル2 = 古典的人工知能 / レベル3 = 機械学習を取り入れたAI / レベル4 = 深層学習を取り入れたAI",
    type: "matching",
    choices: ["a: シンプルな制御", "b: 古典的人工知能", "c: 機械学習を取り入れたAI", "d: 深層学習を取り入れたAI", "e: 汎用人工知能"],
    images: []
  },
  {
    id: "knowledge-pred-01-003",
    source: "知識工学 予想 第01回",
    category: "knowledge-prediction",
    number: 3,
    prompt: "AIブームと中心技術について、正しい組み合わせを答えなさい。",
    answer: "第1次AIブーム = 推論・探索 / 第2次AIブーム = 知識・エキスパートシステム / 第3次AIブーム = 機械学習・特徴表現・深層学習",
    type: "matching",
    choices: ["a: 推論・探索", "b: 知識・エキスパートシステム", "c: 機械学習・特徴表現・深層学習", "d: 量子コンピュータ"],
    images: []
  },
  {
    id: "knowledge-pred-01-004",
    source: "知識工学 予想 第01回",
    category: "knowledge-prediction",
    number: 4,
    prompt: "世界初の汎用コンピュータENIACについて、正式名称として正しいものを選びなさい。",
    answer: "Electronic Numerical Integrator and Computer",
    type: "single",
    choices: ["Electronic Numerical Integrator and Computer", "Expert Network Intelligence and Computer", "Engineering Neural Interface Automatic Calculator", "Electronic Natural Intelligence AI Computer"],
    images: []
  },
  {
    id: "knowledge-pred-01-005",
    source: "知識工学 予想 第01回",
    category: "knowledge-prediction",
    number: 5,
    prompt: "人工知能とロボットの違いについて、スライドの説明に合うものを選びなさい。",
    answer: "ロボットの脳にあたる部分が人工知能であり、AIは目に見えない考える部分を実現する",
    type: "single",
    choices: ["ロボットの脳にあたる部分が人工知能であり、AIは目に見えない考える部分を実現する", "人工知能とロボットは完全に同じ意味である", "ロボットは必ず人工知能を搭載している", "人工知能は機械の身体だけを指す"],
    images: []
  },
  {
    id: "knowledge-pred-02-001",
    source: "知識工学 予想 第02回",
    category: "knowledge-prediction",
    number: 1,
    prompt: "探索問題における用語について、正しい組み合わせを答えなさい。",
    answer: "初期状態 = 探索を開始する状態 / 目標状態 = 到達したい状態 / 状態空間 = 可能な全状態の集合",
    type: "matching",
    choices: ["a: 探索を開始する状態", "b: 到達したい状態", "c: 可能な全状態の集合", "d: 最短経路だけの集合"],
    images: []
  },
  {
    id: "knowledge-pred-02-002",
    source: "知識工学 予想 第02回",
    category: "knowledge-prediction",
    number: 2,
    prompt: "深さ優先探索と幅優先探索について、正しい組み合わせを答えなさい。",
    answer: "深さ優先探索 = メモリ消費量が少ないが遠回りする可能性がある / 幅優先探索 = 最短経路が見つかるがメモリ消費量が多い",
    type: "matching",
    choices: ["a: メモリ消費量が少ないが遠回りする可能性がある", "b: 最短経路が見つかるがメモリ消費量が多い", "c: 常に全探索しない", "d: 学習データから特徴量を抽出する"],
    images: []
  },
  {
    id: "knowledge-pred-02-003",
    source: "知識工学 予想 第02回",
    category: "knowledge-prediction",
    number: 3,
    prompt: "探索木に関する用語について、ノードとエッジの説明を答えなさい。",
    answer: "ノード = 丸で表される点 / エッジ = ノード間を結ぶ線",
    type: "matching",
    choices: ["a: 丸で表される点", "b: ノード間を結ぶ線", "c: 予測対象の変数", "d: データの列"],
    images: []
  },
  {
    id: "knowledge-pred-02-004",
    source: "知識工学 予想 第02回",
    category: "knowledge-prediction",
    number: 4,
    prompt: "8パズルの状態空間は、9種類の値を各マスに重複なく入れる場合として考えると何通りか。式で答えなさい。",
    answer: "9!",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-pred-02-005",
    source: "知識工学 予想 第02回",
    category: "knowledge-prediction",
    number: 5,
    prompt: "Rで X <- c(2, 4, 6, 8, 10) が定義されている。X[3] の実行結果を答えなさい。",
    answer: "6",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-pred-03-001",
    source: "知識工学 予想 第03回",
    category: "knowledge-prediction",
    number: 1,
    prompt: "Mini-Max法について、正しい説明を選びなさい。",
    answer: "自分の番ではスコア最大、相手の番ではスコア最小になるように戦略を立てる",
    type: "single",
    choices: ["自分の番ではスコア最大、相手の番ではスコア最小になるように戦略を立てる", "乱数だけで全ての手を決める", "学習データを用いて回帰直線を求める", "知識ベースを自動削除する"],
    images: []
  },
  {
    id: "knowledge-pred-03-002",
    source: "知識工学 予想 第03回",
    category: "knowledge-prediction",
    number: 2,
    prompt: "エキスパートシステムの構成要素について、正しい組み合わせを答えなさい。",
    answer: "知識ベース = 専門家の知識を格納 / 推論エンジン = ルールやデータから判断 / 説明モジュール = 推論結果の理由を説明",
    type: "matching",
    choices: ["a: 専門家の知識を格納", "b: ルールやデータから判断", "c: 推論結果の理由を説明", "d: 画像を自動生成"],
    images: []
  },
  {
    id: "knowledge-pred-03-003",
    source: "知識工学 予想 第03回",
    category: "knowledge-prediction",
    number: 3,
    prompt: "エキスパートシステムの分類について、正しい組み合わせを答えなさい。",
    answer: "診断型 = 現在のデータをよく説明できる診断を発見 / 設計型 = 条件を満足する設計解を生成 / 制御型 = 知識に基づきリアルタイムで制御",
    type: "matching",
    choices: ["a: 現在のデータをよく説明できる診断を発見", "b: 条件を満足する設計解を生成", "c: 知識に基づきリアルタイムで制御", "d: 文章の続きを生成"],
    images: []
  },
  {
    id: "knowledge-pred-03-004",
    source: "知識工学 予想 第03回",
    category: "knowledge-prediction",
    number: 4,
    prompt: "知識獲得ボトルネックとは何か。要点を説明しなさい。",
    answer: "人間の専門家が持つ暗黙的・経験的な知識を抽出し、知識ベースとして保守する手間やコストが大きすぎるという問題。",
    type: "free",
    choices: [],
    images: []
  },
  {
    id: "knowledge-pred-03-005",
    source: "知識工学 予想 第03回",
    category: "knowledge-prediction",
    number: 5,
    prompt: "意味ネットワークの関係について、正しい組み合わせを答えなさい。",
    answer: "is-a関係 = 上位概念を表す / part-of関係 = 構成要素を表す",
    type: "matching",
    choices: ["a: 上位概念を表す", "b: 構成要素を表す", "c: 予測誤差を表す", "d: 回帰係数を表す"],
    images: []
  },
  {
    id: "knowledge-pred-04-001",
    source: "知識工学 予想 第04回",
    category: "knowledge-prediction",
    number: 1,
    prompt: "機械学習とは何か。スライドの説明に合うものを選びなさい。",
    answer: "AIのプログラム自身が、与えられたデータを通じてデータに潜むパターンを学習する仕組み",
    type: "single",
    choices: ["AIのプログラム自身が、与えられたデータを通じてデータに潜むパターンを学習する仕組み", "人間がすべての判断ルールを手作業で書き込む仕組み", "コンピュータを使わずに数学の証明を行う方法", "データを使わず乱数だけで判断する方法"],
    images: []
  },
  {
    id: "knowledge-pred-04-002",
    source: "知識工学 予想 第04回",
    category: "knowledge-prediction",
    number: 2,
    prompt: "人工知能、機械学習、ニューラルネットワーク、深層学習の位置づけについて、内側に含まれる順に答えなさい。",
    answer: "人工知能 > 機械学習 > ニューラルネットワーク > 深層学習",
    type: "text",
    choices: [],
    images: ["assets/ref-knowledge-neural.svg"]
  },
  {
    id: "knowledge-pred-04-003",
    source: "知識工学 予想 第04回",
    category: "knowledge-prediction",
    number: 3,
    prompt: "大規模言語モデル（LLM）について、事前学習とファインチューニングの説明を答えなさい。",
    answer: "事前学習 = 大量の文章から言語の構造・文法・語彙を学ぶ / ファインチューニング = 特定のタスクや応用分野に焦点を当てて追加訓練する",
    type: "matching",
    choices: ["a: 大量の文章から言語の構造・文法・語彙を学ぶ", "b: 特定のタスクや応用分野に焦点を当てて追加訓練する", "c: 探索木を幅優先でたどる", "d: 回帰係数を手計算する"],
    images: []
  },
  {
    id: "knowledge-pred-04-004",
    source: "知識工学 予想 第04回",
    category: "knowledge-prediction",
    number: 4,
    prompt: "トイ・プロブレムとは何か。最も近い説明を選びなさい。",
    answer: "本質を損なわない程度に簡略化した問題",
    type: "single",
    choices: ["本質を損なわない程度に簡略化した問題", "現実世界の問題を完全に再現した問題", "答えが存在しない問題", "試験に出ない問題"],
    images: []
  },
  {
    id: "knowledge-pred-04-005",
    source: "知識工学 予想 第04回",
    category: "knowledge-prediction",
    number: 5,
    prompt: "強いAIと弱いAIについて、正しい組み合わせを答えなさい。",
    answer: "強いAI = 真に人間と同等の知能や心を持つもの / 弱いAI = 限定的な問題や状況で道具として知的にふるまうもの",
    type: "matching",
    choices: ["a: 真に人間と同等の知能や心を持つもの", "b: 限定的な問題や状況で道具として知的にふるまうもの", "c: 必ず身体を持つもの", "d: 必ず感情を持たないもの"],
    images: []
  },
  {
    id: "knowledge-pred-05-001",
    source: "知識工学 予想 第05回",
    category: "knowledge-prediction",
    number: 1,
    prompt: "フレーム問題で、ロボット1号・2号・3号が失敗した理由について正しい組み合わせを答えなさい。",
    answer: "ロボット1号 = 目的以外のことを推論できなかった / ロボット2号 = 副次的な可能性を考えすぎて時間切れ / ロボット3号 = 目的と無関係かどうかの判断にも時間がかかった",
    type: "matching",
    choices: ["a: 目的以外のことを推論できなかった", "b: 副次的な可能性を考えすぎて時間切れ", "c: 目的と無関係かどうかの判断にも時間がかかった", "d: 学習データが多すぎた"],
    images: []
  },
  {
    id: "knowledge-pred-05-002",
    source: "知識工学 予想 第05回",
    category: "knowledge-prediction",
    number: 2,
    prompt: "線形回帰で用いる用語について、正しい組み合わせを答えなさい。",
    answer: "説明変数 = 予測に使う変数 / 目的変数 = 予測対象の変数",
    type: "matching",
    choices: ["a: 予測に使う変数", "b: 予測対象の変数", "c: 誤差だけを表す変数", "d: 探索木の根"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "knowledge-pred-05-003",
    source: "知識工学 予想 第05回",
    category: "knowledge-prediction",
    number: 3,
    prompt: "単回帰分析と重回帰分析について、正しい組み合わせを答えなさい。",
    answer: "単回帰分析 = 説明変数が1つ / 重回帰分析 = 説明変数が複数",
    type: "matching",
    choices: ["a: 説明変数が1つ", "b: 説明変数が複数", "c: 目的変数が必ず離散値", "d: 探索手法の一種"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "knowledge-pred-05-004",
    source: "知識工学 予想 第05回",
    category: "knowledge-prediction",
    number: 4,
    prompt: "最小二乗法で、残差をそのまま足さずに二乗して足し合わせる理由を説明しなさい。",
    answer: "残差をそのまま足すと正負で打ち消し合って正しく評価できないため。二乗すればすべて正になり、予測値と実際の値のずれを評価できる。",
    type: "free",
    choices: [],
    images: []
  },
  {
    id: "knowledge-pred-05-005",
    source: "知識工学 予想 第05回",
    category: "knowledge-prediction",
    number: 5,
    prompt: "Rで線形回帰を行う lm() 関数について、lm(●~., data=■) の ●、.、■ の意味を答えなさい。",
    answer: "● = 目的変数 / . = 目的変数以外の全変数を説明変数にする / ■ = 分析対象データ",
    type: "matching",
    choices: ["a: 目的変数", "b: 目的変数以外の全変数を説明変数にする", "c: 分析対象データ", "d: 作業ディレクトリ"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "knowledge-pred-06-001",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 1,
    prompt: "エントロピーについて、スライドの説明に合うものを選びなさい。",
    answer: "曖昧さを表す指標で、値が大きいほどランダムに近い状態である",
    type: "single",
    choices: ["曖昧さを表す指標で、値が大きいほどランダムに近い状態である", "予測値と実測値の差だけを表す指標である", "データの列名だけを表す指標である", "常に0になる指標である"],
    images: []
  },
  {
    id: "knowledge-pred-06-002",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 2,
    prompt: "決定木の用語について、正しい組み合わせを答えなさい。",
    answer: "根 = 一番最初の条件分岐を担うノード / 枝 = ノードとノードを結ぶリンク / 葉 = クラスが割り当てられる端点",
    type: "matching",
    choices: ["a: 一番最初の条件分岐を担うノード", "b: ノードとノードを結ぶリンク", "c: クラスが割り当てられる端点", "d: 行列の対角成分"],
    images: ["assets/ref-knowledge-decision-tree.svg"]
  },
  {
    id: "knowledge-pred-06-003",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 3,
    prompt: "決定木で使う属性とクラスについて、正しい組み合わせを答えなさい。",
    answer: "属性 = 特徴量を表す変数 / クラス = 予測されるべき変数",
    type: "matching",
    choices: ["a: 特徴量を表す変数", "b: 予測されるべき変数", "c: 残差平方和", "d: 経路の長さ"],
    images: ["assets/ref-knowledge-decision-tree.svg"]
  },
  {
    id: "knowledge-pred-06-004",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 4,
    prompt: "分類と回帰について、正しい組み合わせを答えなさい。",
    answer: "分類 = 予測対象が離散値 / 回帰 = 予測対象が連続値",
    type: "matching",
    choices: ["a: 予測対象が離散値", "b: 予測対象が連続値", "c: 説明変数が必ず1つ", "d: 木構造を使わない"],
    images: []
  },
  {
    id: "knowledge-pred-06-005",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 5,
    prompt: "ID3アルゴリズムでは、どのような属性を見つけて枝分かれさせるか。",
    answer: "エントロピーが最も小さくなる属性",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-pred-06-006",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 6,
    prompt: "過学習すると何が問題になるか。要点を説明しなさい。",
    answer: "予測モデルが学習データに特化しすぎて、新しいデータに対する予測精度が下がり、汎化性能が落ちる。",
    type: "free",
    choices: [],
    images: ["assets/ref-knowledge-decision-tree.svg"]
  },
  {
    id: "knowledge-pred-06-007",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 7,
    prompt: "Rの決定木分析で、rpart(dat$Survived~., data=dat[, 1:3], method=\"class\") としたとき、method=\"class\" は何を表すか。",
    answer: "分類の決定木",
    type: "single",
    choices: ["分類の決定木", "回帰木", "散布図の描画", "CSVの読み込み"],
    images: ["assets/ref-knowledge-decision-tree.svg"]
  },
  {
    id: "knowledge-pred-06-008",
    source: "知識工学 予想 第06回",
    category: "knowledge-prediction",
    number: 8,
    prompt: "irisデータセットについて、説明変数と目的変数の組み合わせを答えなさい。",
    answer: "説明変数 = Sepal.Length・Sepal.Width・Petal.Length・Petal.Width / 目的変数 = Species",
    type: "matching",
    choices: ["a: Sepal.Length・Sepal.Width・Petal.Length・Petal.Width", "b: Species", "c: Survived", "d: Class・Gender・Age"],
    images: []
  },
  {
    id: "ml-mid-2022-001",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 1,
    prompt: "正解ラベルつきのデータを用いて、新規データがどのクラスに属するかを予測するアルゴリズムを何というか。",
    answer: "分類",
    type: "single",
    choices: ["予測", "関数", "分類", "クラスタリング"],
    images: []
  },
  {
    id: "ml-mid-2022-002",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 2,
    prompt: "スパムメール判定のように、あらかじめ分類済みのデータからルールを学習して新しいデータを判別する学習は何か。",
    answer: "教師あり学習",
    type: "single",
    choices: ["教師あり学習", "教師なし学習", "強化学習", "直行学習"],
    images: []
  },
  {
    id: "ml-mid-2022-003",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 3,
    prompt: "既存データの背後に関数が隠れていると考え、その関数を推定する分析手法は何か。",
    answer: "回帰分析",
    type: "single",
    choices: ["回帰分析", "分類", "教師なし学習", "定数化"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-004",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 4,
    prompt: "回帰分析で、最尤推定法やベイズ推定を用いることで可能になる予測の性質として適切なものを選びなさい。",
    answer: "確率的",
    type: "single",
    choices: ["場当たり的", "独立的", "確率的", "教師なし"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-005",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 5,
    prompt: "データセット (x, t) について、x、t、複数のxをベクトル化したもの、xとtの関係を表す関数の名称を答えなさい。",
    answer: "x = 特徴変数 / t = 目的変数 / 複数のx = 特徴ベクトル / 関係を表す関数 = 目的関数",
    type: "matching",
    choices: ["a: 特徴変数", "b: 目的変数", "c: 特徴ベクトル", "d: 目的関数", "e: パラメータ"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-006",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 6,
    prompt: "統計分析で、データ全体の中心を表す代表値を何というか。",
    answer: "平均値",
    type: "single",
    choices: ["平均値", "偏差", "分散", "標準偏差"],
    images: []
  },
  {
    id: "ml-mid-2022-007",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 7,
    prompt: "各データの値から平均値を引いた値を何というか。",
    answer: "偏差",
    type: "single",
    choices: ["平均値", "偏差", "分散", "標準偏差"],
    images: []
  },
  {
    id: "ml-mid-2022-008",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 8,
    prompt: "偏差の2乗の平均として定義され、データのばらつきを表す量を何というか。",
    answer: "分散",
    type: "single",
    choices: ["平均値", "中央値", "分散", "相関係数"],
    images: []
  },
  {
    id: "ml-mid-2022-009",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 9,
    prompt: "分散の平方根として定義され、元データと同じ単位でばらつきを表す量を何というか。",
    answer: "標準偏差",
    type: "single",
    choices: ["標準偏差", "平均値", "偏差", "目的関数"],
    images: []
  },
  {
    id: "ml-mid-2022-010",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 10,
    prompt: "トレーニングセットの近似曲線 f(x)=Σ w_m x^m について、各観測点との誤差の二乗和を表す誤差関数として適切なものを選びなさい。",
    answer: "E = 1/2 Σ{f(x_n)-t_n}^2",
    type: "single",
    choices: ["E = Σ w_m x^m", "E = 1/2 Σ{f(x_n)-t_n}^2", "E = (Φ^TΦ)^-1Φ^Tt", "E = Σ t_n x_n"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-011",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 11,
    prompt: "最小二乗法で近似曲線を最適化するため、誤差関数に対して行う操作として適切なものを選びなさい。",
    answer: "係数で偏微分し、その値が0になる方程式を求める",
    type: "single",
    choices: ["係数で偏微分し、その値が0になる方程式を求める", "誤差関数をそのまま最大化する", "テストセットだけで係数を決める", "全ての係数を1に固定する"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-012",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 12,
    prompt: "最小二乗法で求めた停留点が極小であることを確認する十分条件として適切なものを選びなさい。",
    answer: "ヘッセ行列が正定値である",
    type: "single",
    choices: ["ヘッセ行列が正定値である", "ヘッセ行列の行列式が必ず0である", "勾配ベクトルが0でない", "係数がすべて負である"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-mid-2022-013",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 13,
    prompt: "次数Mを上げてもトレーニングセットのRMS Errorが十分に下がらない場合の理由として最も適切なものを選びなさい。",
    answer: "トレーニングセットのサンプル数が近似式の次数Mに対して十分に多いため",
    type: "single",
    choices: ["トレーニングセットの分散が大きすぎるため", "トレーニングセットのサンプル数が近似式の次数Mに対して十分に多いため", "トレーニングセットのサンプル数が少なすぎるため", "特徴変数が存在しないため"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-014",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 14,
    prompt: "テストセットのRMS Errorが、ある次数以上でほぼ変化しなくなる場合、最適次数を決める根拠として適切なものを選びなさい。",
    answer: "テストセットのRMS Errorがそれ以上変化しないため、その手前の次数を選ぶ",
    type: "single",
    choices: ["トレーニングセットだけで誤差が最小になる最大次数を選ぶ", "テストセットのRMS Errorがそれ以上変化しないため、その手前の次数を選ぶ", "必ず次数1を選ぶ", "次数はランダムに選ぶ"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-015",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 15,
    prompt: "Pythonで係数表を行方向に見やすく表示するため、データフレーム df_ws を転置して表示するコードとして適切なものを選びなさい。",
    answer: "print(df_ws.transpose())",
    type: "single",
    choices: ["print(df_ws)", "print(df_ws.reverse())", "print(df_ws.transpose())", "print(df_ws.shape())"],
    images: []
  },
  {
    id: "ml-mid-2022-016",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 16,
    prompt: "オーバーフィッティングを防ぐためにクロスバリデーションを使う理由として適切なものを選びなさい。",
    answer: "データを分割して複数回評価し、テストセットの偏りを検出しやすくするため",
    type: "single",
    choices: ["学習データだけで精度を最大化するため", "データを分割して複数回評価し、テストセットの偏りを検出しやすくするため", "全てのデータをテストセットにするため", "モデルの次数を必ず0にするため"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-mid-2022-017",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 17,
    prompt: "クロスバリデーションを厳密に行おうとすると問題になりやすい点として適切なものを選びなさい。",
    answer: "分割パターンの組み合わせが膨大になり、処理時間がかかる",
    type: "single",
    choices: ["データの偏りが必ず消える", "分割パターンの組み合わせが膨大になり、処理時間がかかる", "学習が一切できなくなる", "特徴変数が目的変数になる"],
    images: []
  },
  {
    id: "ml-mid-2022-018",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 18,
    prompt: "x=0のまわりで f(x)=1/(1-x) を3次までテイラー展開した式を選びなさい。",
    answer: "f(x)=1+x+x^2+x^3",
    type: "single",
    choices: ["f(x)=1+x+x^2", "f(x)=1+x+x^2+x^3", "f(x)=1+x+2x^2", "f(x)=1-x+x^2-x^3"],
    images: []
  },
  {
    id: "ml-mid-2022-019",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 19,
    prompt: "f(x)=x^3-3x の停留点を求めなさい。",
    answer: "x = -1, 1",
    type: "single",
    choices: ["x = -1, 1", "x = -2, 2", "x = 0, 3", "x = 1, 2"],
    images: []
  },
  {
    id: "ml-mid-2022-020",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 20,
    prompt: "f(x)=x^3-3x の停留点 x=-1 と x=1 の極値判定として正しいものを選びなさい。",
    answer: "x=-1 は極大値、x=1 は極小値",
    type: "single",
    choices: ["x=-1 は極大値、x=1 は極小値", "x=-1 は極小値、x=1 は極大値", "どちらも極大値", "どちらも極値でない"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-mid-2022-021",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 21,
    prompt: "f(x,y)=x^3+2xy+y^2-x の勾配ベクトルを選びなさい。",
    answer: "(3x^2+2y-1, 2x+2y)",
    type: "single",
    choices: ["(3x^2+2y-1, 2x+2y)", "(3x^2+3y, 2x+3y)", "(3x^3+2y-1, 4x+2y)", "(2x^2+2y, 2x+3y)"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-mid-2022-022",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 22,
    prompt: "f(x,y)=x^3+2xy+y^2-x の停留点を選びなさい。",
    answer: "(1, -1), (-1/3, 1/3)",
    type: "single",
    choices: ["(1, -1), (-1/3, 1/3)", "(1, -1), (1/3, -1/3)", "(-1, -1), (-1/3, 1/3)", "(1, 1), (-1/3, -1/3)"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-mid-2022-023",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 23,
    prompt: "f(x,y)=x^3+2xy+y^2-x のヘッセ行列を選びなさい。",
    answer: "[[6x, 2], [2, 2]]",
    type: "single",
    choices: ["[[6x, 2], [2, 2]]", "[[6x, 2x], [2x, 2]]", "[[6x, 2], [2, 3]]", "[[6, 2], [2, 2]]"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-mid-2022-024",
    source: "機械学習 中間 2022",
    category: "machine-learning",
    number: 24,
    prompt: "f(x,y)=x^3+2xy+y^2-x の停留点 (1,-1) と (-1/3,1/3) の極値判定として正しいものを選びなさい。",
    answer: "(1,-1) は極小値、(-1/3,1/3) は極値でない",
    type: "single",
    choices: ["(1,-1) は極小値、(-1/3,1/3) は極値でない", "(1,-1) は極大値、(-1/3,1/3) は極小値", "どちらも極小値", "どちらも極値でない"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-001",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 1,
    prompt: "機械学習の種類について、正しい組み合わせを答えなさい。\n正解ラベルを用いる学習を（イ）、ラベルなしデータの構造を見つける学習を（ロ）という。",
    answer: "イ = 教師あり学習 / ロ = 教師なし学習",
    type: "matching",
    choices: ["a: 教師あり学習", "b: 教師なし学習", "c: 強化学習", "d: 最小二乗法"],
    images: []
  },
  {
    id: "ml-pred-focus-002",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 2,
    prompt: "分類・回帰分析・クラスタリングについて、正しい組み合わせを答えなさい。",
    answer: "分類 = クラスを予測する / 回帰分析 = 数値を予測する / クラスタリング = 似たデータをグループ化する",
    type: "matching",
    choices: ["a: クラスを予測する", "b: 数値を予測する", "c: 似たデータをグループ化する", "d: 誤差を必ず0にする"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-003",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 3,
    prompt: "新規メールがスパムメールかどうかを、過去の分類済みメールから判定する例はどれに最も近いか。",
    answer: "教師あり学習による分類",
    type: "single",
    choices: ["教師あり学習による分類", "教師なし学習によるクラスタリング", "強化学習による報酬最大化", "正規分布の標準化だけ"],
    images: []
  },
  {
    id: "ml-pred-focus-004",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 4,
    prompt: "データセットで、観測値 x から予測したい値 t を推定する場合、x と t の呼び方として正しい組み合わせを答えなさい。",
    answer: "x = 特徴変数 / t = 目的変数",
    type: "matching",
    choices: ["a: 特徴変数", "b: 目的変数", "c: 誤差関数", "d: 標準偏差"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-005",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 5,
    prompt: "特徴変数が複数あるとき、それらをまとめて表したものを何というか。",
    answer: "特徴ベクトル",
    type: "single",
    choices: ["特徴ベクトル", "目的関数", "ハット行列", "確率密度"],
    images: []
  },
  {
    id: "ml-pred-focus-006",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 6,
    prompt: "データ [2, 4, 6, 8] の平均値を選びなさい。",
    answer: "5",
    type: "single",
    choices: ["4", "5", "6", "20"],
    images: []
  },
  {
    id: "ml-pred-focus-007",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 7,
    prompt: "データ [2, 4, 6, 8] の平均値が5のとき、データ8の偏差を選びなさい。",
    answer: "3",
    type: "single",
    choices: ["-3", "0", "3", "5"],
    images: []
  },
  {
    id: "ml-pred-focus-008",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 8,
    prompt: "分散と標準偏差について、正しい組み合わせを答えなさい。",
    answer: "分散 = 偏差の2乗の平均 / 標準偏差 = 分散の平方根",
    type: "matching",
    choices: ["a: 偏差の2乗の平均", "b: 分散の平方根", "c: 平均の2乗", "d: データ数の平方根"],
    images: []
  },
  {
    id: "ml-pred-focus-009",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 9,
    prompt: "正規分布について、平均と分散がグラフに与える影響として正しい組み合わせを答えなさい。",
    answer: "平均 = 中心位置を決める / 分散 = 広がりを決める",
    type: "matching",
    choices: ["a: 中心位置を決める", "b: 広がりを決める", "c: データ数だけを決める", "d: クラス数だけを決める"],
    images: ["assets/ref-ml-normal-distribution.svg"]
  },
  {
    id: "ml-pred-focus-010",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 10,
    prompt: "ベルヌーイ試行を繰り返したときの成功回数の分布を何というか。",
    answer: "二項分布",
    type: "single",
    choices: ["二項分布", "一様分布", "回帰直線", "ハット行列"],
    images: []
  },
  {
    id: "ml-pred-focus-011",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 11,
    prompt: "補間法と最小二乗法について、正しい説明を選びなさい。",
    answer: "補間法は全ての点を通る関数を求め、最小二乗法は誤差の二乗和が小さい近似関数を求める",
    type: "single",
    choices: ["補間法は全ての点を通る関数を求め、最小二乗法は誤差の二乗和が小さい近似関数を求める", "補間法はテストセットだけを使う方法である", "最小二乗法は分類問題にしか使えない", "最小二乗法では誤差を必ず全て0にする"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-012",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 12,
    prompt: "近似曲線 f(x)=w0+w1x+w2x^2+...+wMx^M において、Mが表すものを選びなさい。",
    answer: "多項式の次数",
    type: "single",
    choices: ["多項式の次数", "データの個数", "目的変数の値", "標準偏差"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-013",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 13,
    prompt: "近似曲線 f(x)=w0+w1x+w2x^2+...+wMx^M において、係数の個数はいくつか。",
    answer: "M+1個",
    type: "single",
    choices: ["M個", "M+1個", "N個", "N-1個"],
    images: []
  },
  {
    id: "ml-pred-focus-014",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 14,
    prompt: "最小二乗法の誤差関数として最も適切なものを選びなさい。",
    answer: "E = 1/2 Σ{f(x_n)-t_n}^2",
    type: "single",
    choices: ["E = 1/2 Σ{f(x_n)-t_n}^2", "E = Σw_m x^m", "E = 平均値 + 分散", "E = x + t"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-015",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 15,
    prompt: "最小二乗法で誤差関数を最小にする係数を求めるため、通常どの条件を用いるか。",
    answer: "各係数で偏微分した値が0になる条件",
    type: "single",
    choices: ["各係数で偏微分した値が0になる条件", "全ての係数を0にする条件", "テストデータを使わない条件", "平均値が必ず0になる条件"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-016",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 16,
    prompt: "行列Φを用いた最小二乗解として、スライドで扱った形に最も近いものを選びなさい。",
    answer: "w = (Φ^TΦ)^-1Φ^Tt",
    type: "single",
    choices: ["w = (Φ^TΦ)^-1Φ^Tt", "w = Φ+t", "w = t^TΦ", "w = Σx_n"],
    images: []
  },
  {
    id: "ml-pred-focus-017",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 17,
    prompt: "RMS Errorは何を表す指標か。",
    answer: "予測値と実測値の平均的なずれの大きさ",
    type: "single",
    choices: ["予測値と実測値の平均的なずれの大きさ", "特徴変数の個数", "分類クラスの名前", "正規分布の中心位置だけ"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-018",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 18,
    prompt: "トレーニングセットとテストセットについて、正しい組み合わせを答えなさい。",
    answer: "トレーニングセット = モデルを学習するデータ / テストセット = 汎化性能を確認するデータ",
    type: "matching",
    choices: ["a: モデルを学習するデータ", "b: 汎化性能を確認するデータ", "c: 必ず削除するデータ", "d: 目的変数だけのデータ"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-019",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 19,
    prompt: "多項式の次数を上げすぎたときに起こりやすい問題を選びなさい。",
    answer: "トレーニングデータに合いすぎて、未知データの予測が悪くなる",
    type: "single",
    choices: ["トレーニングデータに合いすぎて、未知データの予測が悪くなる", "平均値が計算できなくなる", "全てのデータが同じ値になる", "必ず分類問題になる"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-020",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 20,
    prompt: "オーバーフィッティングを見つけるために重要なことを選びなさい。",
    answer: "トレーニングセットだけでなくテストセットの誤差も確認する",
    type: "single",
    choices: ["トレーニングセットだけでなくテストセットの誤差も確認する", "係数を全て同じ値にする", "平均値だけを見ればよい", "特徴変数を必ず1つにする"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-021",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 21,
    prompt: "クロスバリデーションの目的として最も適切なものを選びなさい。",
    answer: "データの分け方による評価の偏りを小さくする",
    type: "single",
    choices: ["データの分け方による評価の偏りを小さくする", "教師なし学習を禁止する", "テストセットを使わないようにする", "誤差関数を消す"],
    images: ["assets/ref-regression.svg"]
  },
  {
    id: "ml-pred-focus-022",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 22,
    prompt: "x=0のまわりで f(x)=1/(1-x) を2次までテイラー展開した式を選びなさい。",
    answer: "1+x+x^2",
    type: "single",
    choices: ["1+x+x^2", "1-x+x^2", "1+x+2x^2", "x+x^2+x^3"],
    images: []
  },
  {
    id: "ml-pred-focus-023",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 23,
    prompt: "テイラー展開は、関数をある点の近くで何として近似する方法か。",
    answer: "多項式",
    type: "single",
    choices: ["多項式", "分類ラベル", "標準偏差", "クラスタ"],
    images: []
  },
  {
    id: "ml-pred-focus-024",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 24,
    prompt: "f(x)=x^2-4x+3 の停留点を選びなさい。",
    answer: "x = 2",
    type: "single",
    choices: ["x = -2", "x = 0", "x = 2", "x = 4"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-025",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 25,
    prompt: "f(x)=x^2-4x+3 の停留点 x=2 の極値判定として正しいものを選びなさい。",
    answer: "極小値",
    type: "single",
    choices: ["極大値", "極小値", "極値でない", "判定不能"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-026",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 26,
    prompt: "停留点について、正しい説明を選びなさい。",
    answer: "1階微分が0になる点だが、必ず極値とは限らない",
    type: "single",
    choices: ["1階微分が0になる点だが、必ず極値とは限らない", "必ず最大値になる点", "必ず最小値になる点", "分散が0になる点"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-027",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 27,
    prompt: "偏微分について、正しい説明を選びなさい。",
    answer: "多変数関数で、1つの変数以外を定数とみなして微分すること",
    type: "single",
    choices: ["多変数関数で、1つの変数以外を定数とみなして微分すること", "全ての変数を同時に足すこと", "平均値を求めること", "標準偏差を求めること"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-028",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 28,
    prompt: "f(x,y)=x^2+xy+y^2 の勾配ベクトルを選びなさい。",
    answer: "(2x+y, x+2y)",
    type: "single",
    choices: ["(2x+y, x+2y)", "(x+y, x+y)", "(2x, 2y)", "(x^2+y, x+y^2)"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-029",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 29,
    prompt: "f(x,y)=x^2+xy+y^2 のヘッセ行列を選びなさい。",
    answer: "[[2, 1], [1, 2]]",
    type: "single",
    choices: ["[[2, 1], [1, 2]]", "[[2x, y], [x, 2y]]", "[[1, 2], [2, 1]]", "[[0, 1], [1, 0]]"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-030",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 30,
    prompt: "勾配ベクトルについて、正しい説明を選びなさい。",
    answer: "各変数で偏微分した成分を並べたベクトルで、関数値が増える向きを表す",
    type: "single",
    choices: ["各変数で偏微分した成分を並べたベクトルで、関数値が増える向きを表す", "観測データの平均だけを表す", "分類ラベルを番号順に並べたもの", "テストセットの個数を表す"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-031",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 31,
    prompt: "ヘッセ行列について、正しい説明を選びなさい。",
    answer: "2階偏微分係数を並べた行列で、極値判定に使われる",
    type: "single",
    choices: ["2階偏微分係数を並べた行列で、極値判定に使われる", "目的変数だけを並べたベクトル", "分類結果の一覧", "正規分布の面積"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-032",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 32,
    prompt: "多変数関数の停留点で、ヘッセ行列が正定値のときの判定として適切なものを選びなさい。",
    answer: "極小値",
    type: "single",
    choices: ["極小値", "極大値", "必ず鞍点", "分類不能"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-033",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 33,
    prompt: "多変数関数の停留点で、ヘッセ行列が負定値のときの判定として適切なものを選びなさい。",
    answer: "極大値",
    type: "single",
    choices: ["極大値", "極小値", "平均値", "テストセット"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-034",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 34,
    prompt: "半正定値行列と正定値行列について、正しい組み合わせを答えなさい。",
    answer: "半正定値 = 二次形式が0以上 / 正定値 = ゼロでないベクトルに対して二次形式が正",
    type: "matching",
    choices: ["a: 二次形式が0以上", "b: ゼロでないベクトルに対して二次形式が正", "c: 全ての成分が0", "d: 必ず逆行列を持たない"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  },
  {
    id: "ml-pred-focus-035",
    source: "機械学習 予想 過去問重点",
    category: "machine-learning-prediction",
    number: 35,
    prompt: "最小二乗法の解が単なる停留点ではなく極小解であることを確認するため、スライドで重視されていた考え方を選びなさい。",
    answer: "勾配ベクトルが0で、ヘッセ行列が正定値であることを確認する",
    type: "single",
    choices: ["勾配ベクトルが0で、ヘッセ行列が正定値であることを確認する", "平均値だけを確認する", "分類ラベルを増やす", "テストセットを全て削除する"],
    images: ["assets/ref-ml-gradient-hessian.svg"]
  }
];
