window.STUDY_EXTRA_QUESTION_DATA = [
  {
    id: "audio-mid-001",
    source: "音声工学 中間",
    category: "audio",
    number: 1,
    prompt: "日本語について、次の空欄に入る組み合わせを答えなさい。\n日本語は世界で（イ）番目に話者数が多いが、系統が（ロ）孤立した言語である。基礎語彙や（ハ）体系はオーストロネシア語族に由来、（ニ）体系はアルタイ諸語に由来すると言われている。",
    answer: "イ = 9 / ロ = 不明な / ハ = 音韻 / ニ = 文法",
    type: "matching",
    choices: ["a: 90", "b: 9", "c: 明らかな", "d: 不明な", "e: 文法", "f: 音韻"],
    images: []
  },
  {
    id: "audio-mid-002",
    source: "音声工学 中間",
    category: "audio",
    number: 2,
    prompt: "音が発生する3つの原因と音声での対応について、正しい組み合わせを答えなさい。\n（イ）物体の振動、（ロ）空気の乱流、（ハ）空気の急激な膨張や収縮。",
    answer: "イ = 母音 / ロ = 摩擦音 / ハ = 破裂音",
    type: "matching",
    choices: ["a: 母音", "b: 摩擦音", "c: 破裂音"],
    images: []
  },
  {
    id: "audio-mid-003",
    source: "音声工学 中間",
    category: "audio",
    number: 3,
    prompt: "「ぴ」の頭子音を有声化した仮名を書きなさい。",
    answer: "び",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-004",
    source: "音声工学 中間",
    category: "audio",
    number: 4,
    prompt: "あらゆる言語の音声を文字で表記するために、国際音声学会が定めた記号を3文字のアルファベットで答えなさい。",
    answer: "IPA",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-005",
    source: "音声工学 中間",
    category: "audio",
    number: 5,
    prompt: "次の語はそれぞれ何モーラか答えなさい。",
    answer: "東京都 = 5 / チョコレート = 5 / 関東 = 4 / サッカー = 4",
    type: "matching",
    choices: ["a: 3", "b: 4", "c: 5", "d: 6"],
    images: []
  },
  {
    id: "audio-mid-006",
    source: "音声工学 中間",
    category: "audio",
    number: 6,
    prompt: "輪状甲状筋が収縮すると、声帯と声はどうなるか。",
    answer: "声帯は膨張し、声は高くなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-007",
    source: "音声工学 中間",
    category: "audio",
    number: 7,
    prompt: "甲状披裂筋が収縮すると、声帯と声はどうなるか。",
    answer: "声帯は収縮し、声は低くなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-008",
    source: "音声工学 中間",
    category: "audio",
    number: 8,
    prompt: "人間が声の高さ（ピッチ）として知覚する物理量は主に何か。",
    answer: "声帯振動の基本周波数(f0)",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-009",
    source: "音声工学 中間",
    category: "audio",
    number: 9,
    prompt: "女性の声帯について、振動部分の長さ・質量・振幅・最高周波数を答えなさい。",
    answer: "長さ = 1 cm / 質量 = 1 g / 振幅 = 1 mm / 最高周波数 = 1 kHz",
    type: "matching",
    choices: ["a: 1 cm", "b: 1 g", "c: 1 mm", "d: 1 kHz"],
    images: []
  },
  {
    id: "audio-mid-010",
    source: "音声工学 中間",
    category: "audio",
    number: 10,
    prompt: "安静呼吸の吸気時に働く筋肉を答えなさい。",
    answer: "横隔膜 / 外肋間筋",
    type: "multiple",
    choices: ["横隔膜", "外肋間筋", "内肋間筋", "腹筋"],
    images: []
  },
  {
    id: "audio-mid-011",
    source: "音声工学 中間",
    category: "audio",
    number: 11,
    prompt: "腹式呼吸では、吸気時と呼気時にそれぞれ何が働くか。",
    answer: "吸気時 = 横隔膜 / 呼気時 = 腹筋",
    type: "matching",
    choices: ["a: 横隔膜", "b: 腹筋", "c: 外肋間筋", "d: 内肋間筋"],
    images: []
  },
  {
    id: "audio-mid-012",
    source: "音声工学 中間",
    category: "audio",
    number: 12,
    prompt: "象の鼻、イカの足、舌のように内部に骨がなく、ほとんどが筋組織からなる組織を何というか。",
    answer: "筋静水圧系",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-013",
    source: "音声工学 中間",
    category: "audio",
    number: 13,
    prompt: "舌の運動について、深層の筋群・浅層の筋群・螺旋状に走る浅層の筋群が収縮した時の動きを答えなさい。",
    answer: "深層の筋群 = 伸張 / 浅層の筋群 = 短縮 / 螺旋状の浅層筋群 = 回旋",
    type: "matching",
    choices: ["a: 伸張", "b: 短縮", "c: 回旋"],
    images: []
  },
  {
    id: "audio-mid-014",
    source: "音声工学 中間",
    category: "audio",
    number: 14,
    prompt: "自己相関係数を用いたピッチ抽出では、シフト量がピッチ周期と一致すると係数はどうなるか。",
    answer: "極大",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-015",
    source: "音声工学 中間",
    category: "audio",
    number: 15,
    prompt: "ケプストラムとは、一般的に音声の対数スペクトルを何したものか。",
    answer: "逆フーリエ変換",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-016",
    source: "音声工学 中間",
    category: "audio",
    number: 16,
    prompt: "ケプストラムの低次成分と高次成分には、それぞれ何の成分が含まれるか。",
    answer: "低次成分 = 声道共鳴 / 高次成分 = 声帯振動",
    type: "matching",
    choices: ["a: 声道共鳴", "b: 声帯振動"],
    images: []
  },
  {
    id: "audio-mid-017",
    source: "音声工学 中間",
    category: "audio",
    number: 17,
    prompt: "線形予測係数は、声道伝達関数を分子が1の何フィルタで表した時の分母の係数か。",
    answer: "IIR",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-018",
    source: "音声工学 中間",
    category: "audio",
    number: 18,
    prompt: "フォルマントとは、母音スペクトルのどの部分か。",
    answer: "山",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-019",
    source: "音声工学 中間",
    category: "audio",
    number: 19,
    prompt: "母音のF1周波数とF2周波数は、それぞれ舌のどの位置を反映するか。",
    answer: "F1 = 上下 / F2 = 前後",
    type: "matching",
    choices: ["a: 上下", "b: 前後"],
    images: []
  },
  {
    id: "audio-mid-020",
    source: "音声工学 中間",
    category: "audio",
    number: 20,
    prompt: "線形予測係数を用いた声道伝達関数の何の周波数が、フォルマントの中心周波数を表すか。",
    answer: "極",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-021",
    source: "音声工学 中間",
    category: "audio",
    number: 21,
    prompt: "/aiueo/を速く、またはあいまいに発話すると、F1-F2平面上の母音5角形の面積はどうなるか。",
    answer: "小さくなる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-022",
    source: "音声工学 中間",
    category: "audio",
    number: 22,
    prompt: "母音5角形は、声道が小さくなると原点からどうなるか。",
    answer: "原点から遠ざかる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-023",
    source: "音声工学 中間",
    category: "audio",
    number: 23,
    prompt: "刺激が連続的であるにもかかわらず、知覚が範疇的に行われることを何というか。",
    answer: "カテゴリ知覚",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-024",
    source: "音声工学 中間",
    category: "audio",
    number: 24,
    prompt: "無声摩擦音 /s/ と /ʃ/、鼻音 /m/ と /n/ の違いは何に現れるか。",
    answer: "スペクトル",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-025",
    source: "音声工学 中間",
    category: "audio",
    number: 25,
    prompt: "破裂音の無声と有声の弁別の手がかりとなる物理量は何か。",
    answer: "VOT",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-mid-026",
    source: "音声工学 中間",
    category: "audio",
    number: 26,
    prompt: "有声破裂音は、後続母音へのF2遷移パターンの違いにより特徴づけられる。この遷移パターンの仮想的な開始点を何というか。",
    answer: "ローカス",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-01-001",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 1,
    prompt: "音声と言語について、正しい組み合わせを答えなさい。\n（イ）は人間の発声器官を用いて発した音、（ロ）は思想・感情・意志などを伝達する記号体系である。",
    answer: "イ = 音声 / ロ = 言語",
    type: "matching",
    choices: ["a: 音声", "b: 言語", "c: 文字", "d: 音素"],
    images: []
  },
  {
    id: "audio-pred-01-002",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 2,
    prompt: "音声工学の主な変換技術について、TTSとSTTの説明を答えなさい。",
    answer: "TTS = 文字言語から音声言語へ変換 / STT = 音声言語から文字言語へ変換",
    type: "matching",
    choices: ["a: 文字言語から音声言語へ変換", "b: 音声言語から文字言語へ変換", "c: 音声から音声へ変換", "d: 文字から文字へ変換"],
    images: []
  },
  {
    id: "audio-pred-01-003",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 3,
    prompt: "語族とは何か。最も近い説明を選びなさい。",
    answer: "共通の祖語から派生した諸言語の総体",
    type: "single",
    choices: ["共通の祖語から派生した諸言語の総体", "文字の形が似ている言語の集合", "話者数が同じくらいの言語の集合", "文法だけが同じ言語の集合"],
    images: []
  },
  {
    id: "audio-pred-01-004",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 4,
    prompt: "日本語の特徴について、正しい組み合わせを答えなさい。",
    answer: "話者数 = 世界第9位 / 系統 = 不明の孤立した言語 / 語順 = SOV型 / 文字体系 = かな・カタカナ・漢字・英数文字を混用",
    type: "matching",
    choices: ["a: 世界第9位", "b: 不明の孤立した言語", "c: SOV型", "d: かな・カタカナ・漢字・英数文字を混用", "e: SVO型"],
    images: []
  },
  {
    id: "audio-pred-01-005",
    source: "音声工学 予想 第01回",
    category: "audio-prediction",
    number: 5,
    prompt: "文字体系について、音節文字・表語文字・表意文字の例を答えなさい。",
    answer: "音節文字 = かな / 表語文字 = 漢字 / 表意文字 = アラビア数字",
    type: "matching",
    choices: ["a: かな", "b: 漢字", "c: アラビア数字", "d: ラテン文字"],
    images: []
  },
  {
    id: "audio-pred-02-001",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 1,
    prompt: "声道を構成する4つの腔をすべて選びなさい。",
    answer: "喉頭腔 / 咽頭腔 / 口腔 / 鼻腔",
    type: "multiple",
    choices: ["喉頭腔", "咽頭腔", "口腔", "鼻腔", "肺胞"],
    images: []
  },
  {
    id: "audio-pred-02-002",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 2,
    prompt: "母音と子音について、正しい説明を答えなさい。",
    answer: "母音 = 声帯振動を音源とし顕著な狭めを持たない言語音 / 子音 = 母音以外の言語音",
    type: "matching",
    choices: ["a: 声帯振動を音源とし顕著な狭めを持たない言語音", "b: 母音以外の言語音", "c: 意味を持つ発音のまとまり", "d: 文字で表した音"],
    images: []
  },
  {
    id: "audio-pred-02-003",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 3,
    prompt: "日本語の音素 /h/ の異音について、「は」「ひ」「ふ」の頭子音の種類を答えなさい。",
    answer: "は = 無声声門摩擦音 / ひ = 無声硬口蓋摩擦音 / ふ = 無声両唇摩擦音",
    type: "matching",
    choices: ["a: 無声声門摩擦音", "b: 無声硬口蓋摩擦音", "c: 無声両唇摩擦音", "d: 無声歯茎摩擦音"],
    images: []
  },
  {
    id: "audio-pred-02-004",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 4,
    prompt: "音素表記では、音素記号を何で前後から挟むか。",
    answer: "/ /",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-02-005",
    source: "音声工学 予想 第02回",
    category: "audio-prediction",
    number: 5,
    prompt: "音節とモーラについて、正しい説明を答えなさい。",
    answer: "音節 = 0個以上のC + 1個のV + 0個以上のC / モーラ = 0〜2個のC + 1個のV、または特殊モーラ",
    type: "matching",
    choices: ["a: 0個以上のC + 1個のV + 0個以上のC", "b: 0〜2個のC + 1個のV、または特殊モーラ", "c: 意味を持つ発音のまとまり", "d: 声の高さの単位"],
    images: []
  },
  {
    id: "audio-pred-03-001",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 1,
    prompt: "喉頭の構造で覚えるべき骨1つと軟骨3つを答えなさい。",
    answer: "骨 = 舌骨 / 軟骨 = 甲状軟骨・輪状軟骨・披裂軟骨",
    type: "matching",
    choices: ["a: 舌骨", "b: 甲状軟骨・輪状軟骨・披裂軟骨", "c: 下顎骨", "d: 口蓋骨・鼻骨・頬骨"],
    images: []
  },
  {
    id: "audio-pred-03-002",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 2,
    prompt: "声門とは何か。",
    answer: "左右の声帯の隙間",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-03-003",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 3,
    prompt: "喉頭の筋肉と作用について、正しい組み合わせを答えなさい。",
    answer: "後輪状披裂筋 = 声門開放 / 外側輪状披裂筋 = 声門閉鎖 / 横披裂筋 = 声門閉鎖 / 輪状甲状筋 = 声帯を伸ばす",
    type: "matching",
    choices: ["a: 声門開放", "b: 声門閉鎖", "c: 声帯を伸ばす", "d: 声帯を縮める"],
    images: []
  },
  {
    id: "audio-pred-03-004",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 4,
    prompt: "声帯筋・甲状披裂筋（TA）は声帯にどのように作用するか。",
    answer: "声帯を縮める",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-03-005",
    source: "音声工学 予想 第03回",
    category: "audio-prediction",
    number: 5,
    prompt: "ピッチとして知覚される主な物理量と、声帯振動がない場合の知覚について答えなさい。",
    answer: "主な物理量 = 声帯振動の基本周波数 / 声帯振動がない場合 = ピッチ感なし",
    type: "matching",
    choices: ["a: 声帯振動の基本周波数", "b: ピッチ感なし", "c: 音圧レベル", "d: 声道長"],
    images: []
  },
  {
    id: "audio-pred-04-001",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 1,
    prompt: "ヒトの声道は、口腔から咽頭腔にかけて約何度に屈曲しているか。",
    answer: "90度",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-04-002",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 2,
    prompt: "肺の構造について、左右の葉の数を答えなさい。",
    answer: "右 = 三葉 / 左 = 二葉",
    type: "matching",
    choices: ["a: 三葉", "b: 二葉", "c: 一葉", "d: 四葉"],
    images: []
  },
  {
    id: "audio-pred-04-003",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 3,
    prompt: "呼吸様式と働く筋について、正しい組み合わせを答えなさい。",
    answer: "安静呼吸の吸気 = 外肋間筋・横隔膜 / 胸式深呼吸の呼気 = 内肋間筋 / 腹式深呼吸の呼気 = 腹筋",
    type: "matching",
    choices: ["a: 外肋間筋・横隔膜", "b: 内肋間筋", "c: 腹筋", "d: 声帯筋"],
    images: []
  },
  {
    id: "audio-pred-04-004",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 4,
    prompt: "発話時、軟口蓋はどのように動き、何を閉鎖するか。",
    answer: "挙上し、鼻腔への入り口を閉鎖する",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-04-005",
    source: "音声工学 予想 第04回",
    category: "audio-prediction",
    number: 5,
    prompt: "鼻腔・副鼻腔について、鼻腔を左右に二分するものと、周囲の骨の中の空間を答えなさい。",
    answer: "左右に二分するもの = 鼻中隔 / 周囲の骨の中の空間 = 副鼻腔",
    type: "matching",
    choices: ["a: 鼻中隔", "b: 副鼻腔", "c: 口蓋垂", "d: 舌骨"],
    images: []
  },
  {
    id: "audio-pred-05-001",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 1,
    prompt: "音の3属性と、それに対応する物理的特徴を答えなさい。",
    answer: "大きさ = 音圧 / 高さ = 基本周波数 / 音色 = スペクトル",
    type: "matching",
    choices: ["a: 音圧", "b: 基本周波数", "c: スペクトル", "d: 声道長"],
    images: []
  },
  {
    id: "audio-pred-05-002",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 2,
    prompt: "最小可聴音圧値はいくらか。単位付きで答えなさい。",
    answer: "2 × 10^-5 Pa",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-05-003",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 3,
    prompt: "通常の会話の音圧レベルはおよそ何dBか。",
    answer: "60 dB",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-05-004",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 4,
    prompt: "代表的なピッチ抽出法について、処理の種類と方法の組み合わせを答えなさい。",
    answer: "波形処理 = 零交叉法 / 相関処理 = 自己相関法・AMDF法 / スペクトル処理 = ケプストラム",
    type: "matching",
    choices: ["a: 零交叉法", "b: 自己相関法・AMDF法", "c: ケプストラム", "d: LPC"],
    images: []
  },
  {
    id: "audio-pred-05-005",
    source: "音声工学 予想 第05回",
    category: "audio-prediction",
    number: 5,
    prompt: "自己相関法で、シフト量kが音声信号の周期に一致すると自己相関係数はどうなるか。",
    answer: "極大になる",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-06-001",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 1,
    prompt: "フォルマントについて、正しい説明を答えなさい。",
    answer: "音声スペクトルの山で、声道の共鳴に由来する",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-06-002",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 2,
    prompt: "母音5角形について、F1・F2と舌の位置の対応を答えなさい。",
    answer: "F1 = 舌の上下位置 / F2 = 舌の前後位置",
    type: "matching",
    choices: ["a: 舌の上下位置", "b: 舌の前後位置", "c: 声帯の開閉", "d: 口唇の丸め"],
    images: []
  },
  {
    id: "audio-pred-06-003",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 3,
    prompt: "日本語5母音は、ほぼどのフォルマントだけで弁別可能か。",
    answer: "F1とF2",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "audio-pred-06-004",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 4,
    prompt: "無声摩擦音 /s/ と /ʃ/ のスペクトルの違いについて、正しい組み合わせを答えなさい。",
    answer: "/s/ = 6 kHz以上にピーク / /ʃ/ = 4 kHz付近にピーク",
    type: "matching",
    choices: ["a: 6 kHz以上にピーク", "b: 4 kHz付近にピーク", "c: 1 kHz付近にピーク", "d: ピークを持たない"],
    images: []
  },
  {
    id: "audio-pred-06-005",
    source: "音声工学 予想 第06回",
    category: "audio-prediction",
    number: 5,
    prompt: "有声摩擦音では、摩擦音のスペクトルに何が重畳するか。",
    answer: "声帯振動の倍音成分や声道共鳴",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-001",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 1,
    prompt: "人工知能を表すAIとは何という英単語の略か。2スペルアウトして答えなさい。",
    answer: "artificial intelligence",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-002",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 2,
    prompt: "人工知能で何か新しいことが実現され、その原理が分かってしまうと「それは知能ではない」と思ってしまう人間心理を何というか。",
    answer: "AI効果",
    type: "single",
    choices: ["R2D2効果", "AI効果", "イライザ効果", "ピグマリオン効果", "バンドワゴン効果"],
    images: []
  },
  {
    id: "knowledge-mid-003",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 3,
    prompt: "探索問題などの問題解決において、到達可能で考察の対象となる状況全ての集合を何というか。",
    answer: "状態空間",
    type: "single",
    choices: ["指数集合", "目標状態", "組合せ爆発", "指数関数", "初期状態", "状態空間"],
    images: []
  },
  {
    id: "knowledge-mid-004",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 4,
    prompt: "Rで次の行列Bが定義されている。\nB = [1 0 2; 2 0 1]\nB[2, 1] の実行結果を答えなさい。",
    answer: "2",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-005",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 5,
    prompt: "Rで次の行列Aが定義されている。\nA = [0 3 0 1; 1 2 0 2; 1 1 1 1; 2 2 3 3; 1 0 1 0; 0 1 0 1]\nmax(A[, 2]) の実行結果を答えなさい。",
    answer: "3",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-006",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 6,
    prompt: "Rで次の行列Bが定義されている。\nB = [1 0 2; 2 0 1]\nmean(B[1, ]) の実行結果を答えなさい。",
    answer: "1",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-007",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 7,
    prompt: "Rで次の行列Aが定義されている。\nA = [0 3 0 1; 1 2 0 2; 1 1 1 1; 2 2 3 3; 1 0 1 0; 0 1 0 1]\njyo=(A[,1]>=1); max(A[jyo, 2]) の実行結果を答えなさい。",
    answer: "2",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-008",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 8,
    prompt: "予測モデルA y = 2800x1 + 170x2 - 10500x3 + 350 を用いる。平均気温x1=25、平均湿度x2=70、曜日x3=0のとき、電力需要量yを求めなさい。",
    answer: "82250",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-009",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 9,
    prompt: "予測モデルBは次の決定木である。\n最初にx1<26なら左、x1>=26なら右へ進む。左側はx3=0ならx2で分岐し、x2<65なら69000、x2>=65なら75000、x3=1なら80000。右側はx1<30ならx2で分岐し、x2<70なら90000、x2>=70なら130000、x1>=30なら145000。\nx1=29、x2=80、x3=0のとき、電力需要量を求めなさい。",
    answer: "130000",
    type: "text",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-010",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 10,
    prompt: "予測モデルAは重回帰式、予測モデルBは木構造で連続値を予測するモデルである。予測モデルBを何と呼ぶか。",
    answer: "回帰木",
    type: "single",
    choices: ["判別木", "ニューラルネットワーク", "深層学習", "回帰木", "クラスタリング", "決定木", "パーセプトロン"],
    images: []
  },
  {
    id: "knowledge-mid-011",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 11,
    prompt: "手順に従ってあらかじめ用意された処理をするだけのチャットボットプログラムは何と呼ばれるか。また、本物の人間と話していると錯覚することを何効果というか。",
    answer: "オ = 人工無脳 / カ = イライザ効果",
    type: "matching",
    choices: ["a: 人工無脳", "b: 人工知能", "c: チャットワーク", "d: 機械学習", "e: ディープラーニング", "f: イライザ効果", "g: チューリング", "h: エニアック"],
    images: []
  },
  {
    id: "knowledge-mid-012",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 12,
    prompt: "2012年、画像認識競技会ILSVRCで、カナダのトロント大学教授である（ウ）が率いるSuperVisionが圧勝した。これが現代AIにおける（エ）ブームの火付け役となった。",
    answer: "ウ = ジェフリー・ヒントン / エ = ディープラーニング",
    type: "matching",
    choices: ["a: マーヴィン・ミンスキー", "b: ジョン・マッカーシー", "c: フランキ・サイワ", "d: ジェフリー・ヒントン", "e: アラン・チューリング", "f: パーセプトロン", "g: 機械学習", "h: ディープラーニング", "i: IT"],
    images: []
  },
  {
    id: "knowledge-mid-013",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 13,
    prompt: "別の場所にいる人間がコンピュータと会話し、相手がコンピュータと見抜けなければコンピュータには人間と同等な知能があると考える評価法を何というか。",
    answer: "チューリングテスト",
    type: "single",
    choices: ["中国語の部屋", "微分の部屋", "AI評価", "チューリングテスト", "りんなテスト", "AI効果"],
    images: []
  },
  {
    id: "knowledge-mid-014",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 14,
    prompt: "「AI自身が、今しようとしていることに関係のあることがらだけを選び出すことは非常に難しい」ことを表すAI分野の難問を何というか。",
    answer: "フレーム問題",
    type: "single",
    choices: ["フレーム問題", "身体性", "特徴量設計", "中国語の部屋", "シンギュラリティ"],
    images: []
  },
  {
    id: "knowledge-mid-015",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 15,
    prompt: "スライドで示されたボードゲームの状態空間の大きさについて、大きい順に並べなさい。",
    answer: "1 = 将棋 / 2 = 囲碁 / 3 = チェス / 4 = オセロ",
    type: "matching",
    choices: ["a: 将棋", "b: 囲碁", "c: チェス", "d: オセロ"],
    images: []
  },
  {
    id: "knowledge-mid-016",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 16,
    prompt: "機械学習では学習に利用できる（ア）が多ければ多いほど望ましい学習結果が得られる。（イ）の発展とともに利用可能な（ア）の種類と量が爆発的に増加した。",
    answer: "ア = データ / イ = インターネット",
    type: "matching",
    choices: ["a: コンピュータ", "b: サーバ", "c: 通信容量", "d: データ", "e: モデル", "f: ネットカフェ", "g: 検索エンジン", "h: データセンター", "i: インターネット", "j: クラウドコンピューティング", "k: ネットカフェ難民", "l: 通信帯域"],
    images: []
  },
  {
    id: "knowledge-mid-017",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 17,
    prompt: "2変数関数 z = 3x^2 - 5y^3 + x - y^2 + 3 の偏導関数 ∂z/∂y として適切なものを選びなさい。",
    answer: "-15y^2 - 2y",
    type: "single",
    choices: ["6x - 5y^3 + 1 - y^2", "-15y^2 - 2y + 6x", "6x + 1", "-15y^2 - 2y", "-15y^2 - 2y + 6x + 3", "6x - 15y^2 + 1 - 2y"],
    images: []
  },
  {
    id: "knowledge-mid-018",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 18,
    prompt: "ジョン・サールは、人間と同等に本物の心を持つ人工知能を（ス）と呼び、これは実現不可能であると主張した。サールは（セ）という思考実験を通じて主張を説明した。",
    answer: "ス = 強い人工知能 / セ = 中国語の部屋",
    type: "matching",
    choices: ["a: 特化型人工知能", "b: 汎用人工知能", "c: 弱い人工知能", "d: 強い人工知能", "e: 汎用テスト", "f: 中国語の部屋", "g: 微子の部屋", "h: 英語の部屋", "i: チューリングテスト", "j: 期末テスト"],
    images: []
  },
  {
    id: "knowledge-mid-019",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 19,
    prompt: "ニューラルネットワークの教師あり学習では、どのアルゴリズムが広く利用されているか。",
    answer: "誤差逆伝播法",
    type: "single",
    choices: ["最尤法", "誤差逆伝播法", "ID3アルゴリズム", "誤差伝搬法", "最小二乗法"],
    images: []
  },
  {
    id: "knowledge-mid-020",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 20,
    prompt: "次の行列が定義されている。\nA = [0 3; 1 2], B = [1 0; 0 2]\nA + B = [a b; c d] としたとき、aに当てはまる値を選びなさい。",
    answer: "a = 1",
    type: "single",
    choices: ["a = 3", "a = 2", "a = 1", "a = 0", "a = 4"],
    images: []
  },
  {
    id: "knowledge-mid-021",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 21,
    prompt: "次の行列が定義されている。\nA = [0 3; 1 2], B = [1 0; 0 2]\nAB = [a b; c d] としたとき、cに当てはまる値を選びなさい。",
    answer: "c = 1",
    type: "single",
    choices: ["c = 6", "c = 3", "c = 0", "c = 1", "c = 2", "c = 5", "c = 4"],
    images: []
  },
  {
    id: "knowledge-mid-022",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 22,
    prompt: "「人工知能」という言葉は1956年にアメリカで開催された（キ）において、著名なアメリカ人工知能科学者（ク）によって初めて使われた。",
    answer: "キ = ダートマス会議 / ク = ジョン・マッカーシー",
    type: "matching",
    choices: ["a: AI会議", "b: ダートマス会議", "c: AAAI", "d: ボストン会議", "e: ダボス会議", "f: フランキ・サイワ", "g: ジョン・マッカーシー", "h: ジェフリー・ヒントン", "i: クロード・シャノン", "j: マーヴィン・ミンスキー"],
    images: []
  },
  {
    id: "knowledge-mid-023",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 23,
    prompt: "データを表す変数 x1, x2, x3 を用いて変数 y の値を求める線形回帰式 y = a1x1 + a2x2 + a3x3 + b が得られた。このとき、x1, x2, x3を何と呼び、yを何と呼ぶか。",
    answer: "ケ = 説明変数 / コ = 目的変数",
    type: "matching",
    choices: ["a: 切片", "b: 偏回帰係数", "c: 傾き", "d: 決定係数", "e: 説明変数", "f: 目的変数"],
    images: []
  },
  {
    id: "knowledge-mid-024",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 24,
    prompt: "米国の思想家レイ・カーツワイルが主張する人工知能におけるシンギュラリティとは何か。要点を説明しなさい。",
    answer: "人工知能が十分に賢くなり、自分自身より賢い人工知能を作れるようになって、技術開発速度が爆発的に加速し、人間の想像を超える知性が生まれるという仮説。",
    type: "free",
    choices: [],
    images: []
  },
  {
    id: "knowledge-mid-025",
    source: "知識工学 中間過去問",
    category: "knowledge",
    number: 25,
    prompt: "ジョン・サールがチューリングテストを批判した理由を説明しなさい。",
    answer: "外から会話が成立しているように見えても、内部では記号を手順通り処理しているだけで意味を理解しているとは限らないため。中国語の部屋の思考実験でこの点を示した。",
    type: "free",
    choices: [],
    images: []
  }
];
